<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>$(NamespacePrefix)</RootNamespace>
		<AssemblyName>$(NamespacePrefix).$(MSBuildThisFileDirectory).5</AssemblyName>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" />
	</ItemGroup>
</Project>
