<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Admin.SqlServer\Admin.SqlServer.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="TUnit.Core" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
	</ItemGroup>
</Project>
