<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
	<ItemGroup>
		<Compile
			Include="..\..\tests\SharedTestingFramework\ContainerHelper.Resources.cs"
			Link="Extensions\Purview\EventSourcing\ContainerHelper.Resources.cs"
		/>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Aspire.Hosting" />
		<PackageReference Include="Aspire.Hosting.Azure.Storage" />
		<PackageReference Include="Aspire.Hosting.Redis" />
		<PackageReference Include="Aspire.Hosting.SqlServer" />
		<PackageReference Include="AspireC4.Hosting" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Samples.Web\Samples.Web.csproj" />
	</ItemGroup>
</Project>
