<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Label="NuGet Package Values">
		<IsPackable>true</IsPackable>
		<Title>Purview Event Store for MongoDB</Title>
		<Description>MongoDB event stream and snapshot storage provider for Purview EventSourcing.</Description>
		<PackageTags>$(PackageTags);purview;dotnet;event-sourcing;event-store;mongodb;events;snapshots;</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\EventSourcing\EventSourcing.csproj" />
		<ProjectReference Include="..\ImplementationShared\ImplementationShared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="LinqKit" />
		<PackageReference Include="MongoDB.Driver" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Options" />
	</ItemGroup>
</Project>
