using Microsoft.CodeAnalysis.Text;
using Purview.EventSourcing.EntityFrameworkCore.SourceGenerator.Heleprs;

namespace Purview.EventSourcing.EntityFrameworkCore.SourceGenerator.Emitters;

static class AttributeEmiiter
{
	public static IEnumerable<(string HintName, SourceText Source)> GetAttributeSources()
	{
		yield return (GetHintName(TypeLibrary.EFOpaqueAttribute), GetEFOpaqueAttributeSource());
	}

	static SourceText GetEFOpaqueAttributeSource()
	{
		var writer = CreateCodeWriter();

		writer
			.WriteFileScopedNamespace(TypeLibrary.EFOpaqueAttribute)
			.XmlSummary(
				"Marks a property to be persisted as an opaque JSON value by the Entity Framework",
				"snapshot providers."
			)
			.XmlRemarks(
				CodeWriter.XmlInlinePara(
					"Members within an opaque property cannot be used in generated snapshot query",
					"expressions. When those members must be queryable, expose a separately mapped",
					"query property or model key/value data as a collection of complex entry objects."
				)
			)
			.XmlExample(
				CodeWriter.XmlInlineCodeBlock(
					$"[{TypeLibrary.EFOpaqueAttribute.Name}]",
					CodeWriter.XmlText(
						"public IReadOnlyDictionary<PlatformID, int> OperatingSystemDistribution { get; init; }"
					)
				)
			)
			.WriteAttributeClass(
				new(TypeLibrary.EFOpaqueAttribute),
				AttributeTargets.Property,
				inherited: true,
				bodyWriter: static writer => writer.Comment("Empty")
			);

		return writer;
	}

	static CodeWriter CreateCodeWriter()
	{
		CodeWriter writer = new(typeof(EFSourceGenerator).FullName, AssemblyInfo.Version);

		writer.WriteAutoGeneratedHeader();

		return writer;
	}

	static string GetHintName(TypeIdentity identity) => $"{identity.Name}.g.cs";
}
