using System.Text;
using Microsoft.CodeAnalysis;

namespace Purview.EventSourcing.SourceGenerator.ValueObject;

static partial class ComplexValueObjectEmitter
{
	public static string Emit(ComplexValueObjectModel model)
	{
		StringBuilder sb = new();
		var indent = model.TypeModel.Namespace is null ? string.Empty : "	";

		EmitHeader(sb, model, indent);
		EmitOnNormalizeDeclaration(sb, model, indent);
		EmitCreateFactory(sb, model, indent);
		EmitOnValidateDeclaration(sb, model, indent);
		EmitHydrateFactory(sb, model, indent);
		EmitEmpty(sb, model, indent);
		EmitConstructor(sb, model, indent);
		EmitEfConstructor(sb, model, indent);
		EmitEquality(sb, model, indent);
		EmitOperators(sb, model, indent);
		EmitComparison(sb, model, indent);
		EmitJsonConverter(sb, model, indent);
		EmitFooter(sb, model, indent);

		return sb.ToString();
	}

	static void EmitHeader(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		if (model.TypeModel.Namespace is not null)
		{
			sb.AppendLine($"namespace {model.TypeModel.Namespace}");
			sb.AppendLine("{");
		}

		if (model.Options.GenerateJsonConverter && !model.HasJsonConverterAttribute)
			sb.AppendLine(
				$"{indent}[global::System.Text.Json.Serialization.JsonConverter(typeof({model.TypeModel.Name}JsonConverter))]"
			);

		var valueObjectSelfEquatableInterface =
			model.TypeSymbol.TypeKind == TypeKind.Struct
			&& !ValueObjectSymbolInspector.ImplementsSelfEquatable(model.TypeSymbol)
				? $", global::System.IEquatable<{model.TypeName}>"
				: string.Empty;
		sb.AppendLine(
			$"{indent}{model.TypeModel.DeclarationPrefix} : global::Purview.EventSourcing.ValueObjects.IValueObject<{model.TypeName}>{valueObjectSelfEquatableInterface}, global::System.IComparable<{model.TypeName}>, global::System.IComparable"
		);
		sb.AppendLine($"{indent}{{");
	}

	static void EmitOnNormalizeDeclaration(
		StringBuilder sb,
		ComplexValueObjectModel model,
		string indent
	)
	{
		if (!model.DeclareOnNormalize)
			return;

		var normalizeParams = string.Join(
			", ",
			model.PropertyTypeNames.Zip(
				model.PropertyNames,
				static (type, name) => $"ref {type} {ValueObjectSymbolInspector.ToCamelCase(name)}"
			)
		);
		sb.AppendLine($"{indent}	static partial void OnNormalize({normalizeParams});");
		sb.AppendLine();
	}

	static void EmitCreateFactory(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (model.CreateExists)
			return;

		var createParams = string.Join(
			", ",
			model.PropertyTypeNames.Zip(
				model.PropertyNames,
				static (type, name) => $"{type} {ValueObjectSymbolInspector.ToCamelCase(name)}"
			)
		);
		var createArgs = string.Join(
			", ",
			model.PropertyNames.Select(ValueObjectSymbolInspector.ToCamelCase)
		);
		var normalizeInvocation =
			model.PropertyNames.Length == 0
				? "OnNormalize();"
				: $"OnNormalize(ref {string.Join(", ref ", model.PropertyNames.Select(ValueObjectSymbolInspector.ToCamelCase))});";
		sb.AppendLine(
			$@"{indent}	public static {model.TypeName} Create({createParams})
{indent}	{{
{indent}		{normalizeInvocation}
{indent}		var result = new {model.TypeName}({createArgs});
{indent}		result.OnValidate({createArgs});
{indent}		return result;
{indent}	}}"
		);
		sb.AppendLine();
	}

	static void EmitOnValidateDeclaration(
		StringBuilder sb,
		ComplexValueObjectModel model,
		string indent
	)
	{
		if (
			!ValueObjectSymbolInspector.ShouldEmitComplexHookDeclaration(
				model.TypeSymbol,
				"OnValidate",
				model.PropertyNames.Length
			)
		)
			return;

		var validateParams = string.Join(
			", ",
			model.PropertyTypeNames.Zip(
				model.PropertyNames,
				static (type, name) => $"{type} {ValueObjectSymbolInspector.ToCamelCase(name)}"
			)
		);
		var validateReadOnly =
			model.TypeSymbol.TypeKind == TypeKind.Struct
			&& ValueObjectSymbolInspector.IsComplexHookReadOnly(
				model.TypeSymbol,
				"OnValidate",
				model.PropertyNames.Length
			);
		var readOnlyPrefix = validateReadOnly ? "readonly " : string.Empty;
		sb.AppendLine(
			$"{indent}	[global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Performance\", \"CA1822:Mark members as static\")]"
		);
		sb.AppendLine($"{indent}	{readOnlyPrefix}partial void OnValidate({validateParams});");
		sb.AppendLine();
	}

	static void EmitHydrateFactory(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (model.HydrateExists)
			return;

		var hydrateParams = string.Join(
			", ",
			model.PropertyTypeNames.Zip(
				model.PropertyNames,
				static (type, name) => $"{type} {ValueObjectSymbolInspector.ToCamelCase(name)}"
			)
		);
		var hydrateArgs = string.Join(
			", ",
			model.PropertyNames.Select(ValueObjectSymbolInspector.ToCamelCase)
		);
		sb.AppendLine(
			$@"{indent}	public static {model.TypeName} Hydrate({hydrateParams})
{indent}	{{
{indent}		return new({hydrateArgs});
{indent}	}}"
		);
		sb.AppendLine();
	}

	static void EmitEmpty(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (
			model.Options.GenerateEmpty
			&& !ValueObjectSymbolInspector.HasMemberWithName(model.TypeSymbol, "Empty")
		)
		{
			var emptyArgs = string.Join(
				", ",
				model.Properties.Select(static property =>
					ValueObjectSymbolInspector.GetEmptyValueExpression(property.Type)
				)
			);
			sb.AppendLine(
				$"{indent}	public static {model.TypeName} Empty => Hydrate({emptyArgs});"
			);
			sb.AppendLine();
		}
	}

	static void EmitConstructor(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (model.CtorExists || model.PropertyNames.Length == 0)
			return;

		var ctorParams = string.Join(
			", ",
			model.PropertyTypeNames.Zip(
				model.PropertyNames,
				static (type, name) => $"{type} {ValueObjectSymbolInspector.ToCamelCase(name)}"
			)
		);
		sb.AppendLine();
		sb.AppendLine(
			$@"{indent}	private {model.TypeModel.Name}({ctorParams})
{indent}	{{"
		);
		foreach (var propertyName in model.PropertyNames)
			sb.AppendLine(
				$"{indent}		{propertyName} = {ValueObjectSymbolInspector.ToCamelCase(propertyName)};"
			);
		sb.AppendLine($"{indent}	}}");
	}

	static void EmitEfConstructor(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (
			!model.Options.GenerateConstructor
			|| model.ParameterlessCtorExists
			|| !ValueObjectSymbolInspector.TryGetEfConstructorArguments(
				model.TypeSymbol,
				model.Properties,
				out var efCtorArguments
			)
		)
			return;

		var efCtorAccessibility =
			model.TypeSymbol.TypeKind == TypeKind.Struct ? "public" : "private";
		sb.AppendLine();
		sb.AppendLine($"{indent}	/// <summary>");
		sb.AppendLine($"{indent}	/// Parameterless constructor for EF Core deserialization.");
		sb.AppendLine(
			$"{indent}	/// This constructor is required to work around EF Core's ConstructorBindingConvention,"
		);
		sb.AppendLine(
			$"{indent}	/// which cannot bind complex type parameters during JSON deserialization."
		);
		sb.AppendLine(
			$"{indent}	/// EF Core uses this parameterless constructor to instantiate the value object,"
		);
		sb.AppendLine($"{indent}	/// then sets properties directly from the JSON payload.");
		sb.AppendLine($"{indent}	/// </summary>");
		sb.AppendLine(
			$@"{indent}	{efCtorAccessibility} {model.TypeModel.Name}() : this({efCtorArguments})
{indent}	{{"
		);
		sb.AppendLine($"{indent}	}}");
	}

	static void EmitFooter(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		sb.AppendLine($"{indent}}}");
		if (model.TypeModel.Namespace is not null)
			sb.AppendLine("}");
	}
}
