using System.Text;
using Microsoft.CodeAnalysis;

namespace Purview.EventSourcing.SourceGenerator.ValueObject;

static class ComplexValueObjectEmitter
{
	public static string Emit(ComplexValueObjectModel model)
	{
		StringBuilder sb = new();
		var indent = model.TypeModel.Namespace is null ? string.Empty : "	";

		EmitHeader(sb, model, indent);
		EmitOnNormalizeDeclaration(sb, model, indent);
		EmitCreateFactory(sb, model, indent);
		EmitOnValidateDeclaration(sb, model, indent);
		EmitHydrateFactory(sb, model, indent);
		EmitEmpty(sb, model, indent);
		EmitConstructor(sb, model, indent);
		EmitEfConstructor(sb, model, indent);
		EmitEquality(sb, model, indent);
		EmitOperators(sb, model, indent);
		EmitComparison(sb, model, indent);
		EmitJsonConverter(sb, model, indent);
		EmitFooter(sb, model, indent);

		return sb.ToString();
	}

	static void EmitHeader(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		if (model.TypeModel.Namespace is not null)
		{
			sb.AppendLine($"namespace {model.TypeModel.Namespace}");
			sb.AppendLine("{");
		}

		if (model.Options.GenerateJsonConverter && !model.HasJsonConverterAttribute)
			sb.AppendLine(
				$"{indent}[global::System.Text.Json.Serialization.JsonConverter(typeof({model.TypeModel.Name}JsonConverter))]"
			);

		var valueObjectSelfEquatableInterface =
			model.TypeSymbol.TypeKind == TypeKind.Struct
			&& !ValueObjectSymbolInspector.ImplementsSelfEquatable(model.TypeSymbol)
				? $", global::System.IEquatable<{model.TypeName}>"
				: string.Empty;
		sb.AppendLine(
			$"{indent}{model.TypeModel.DeclarationPrefix} : global::Purview.EventSourcing.ValueObjects.IValueObject<{model.TypeName}>{valueObjectSelfEquatableInterface}, global::System.IComparable<{model.TypeName}>, global::System.IComparable"
		);
		sb.AppendLine($"{indent}{{");
	}

	static void EmitOnNormalizeDeclaration(
		StringBuilder sb,
		ComplexValueObjectModel model,
		string indent
	)
	{
		if (!model.DeclareOnNormalize)
			return;

		var normalizeParams = string.Join(
			", ",
			model.PropertyTypeNames.Zip(
				model.PropertyNames,
				static (type, name) => $"ref {type} {ValueObjectSymbolInspector.ToCamelCase(name)}"
			)
		);
		sb.AppendLine($"{indent}	static partial void OnNormalize({normalizeParams});");
		sb.AppendLine();
	}

	static void EmitCreateFactory(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (model.CreateExists)
			return;

		var createParams = string.Join(
			", ",
			model.PropertyTypeNames.Zip(
				model.PropertyNames,
				static (type, name) => $"{type} {ValueObjectSymbolInspector.ToCamelCase(name)}"
			)
		);
		var createArgs = string.Join(
			", ",
			model.PropertyNames.Select(ValueObjectSymbolInspector.ToCamelCase)
		);
		var normalizeInvocation =
			model.PropertyNames.Length == 0
				? "OnNormalize();"
				: $"OnNormalize(ref {string.Join(", ref ", model.PropertyNames.Select(ValueObjectSymbolInspector.ToCamelCase))});";
		sb.AppendLine(
			$@"{indent}	public static {model.TypeName} Create({createParams})
{indent}	{{
{indent}		{normalizeInvocation}
{indent}		var result = new {model.TypeName}({createArgs});
{indent}		result.OnValidate({createArgs});
{indent}		return result;
{indent}	}}"
		);
		sb.AppendLine();
	}

	static void EmitOnValidateDeclaration(
		StringBuilder sb,
		ComplexValueObjectModel model,
		string indent
	)
	{
		if (
			!ValueObjectSymbolInspector.ShouldEmitComplexHookDeclaration(
				model.TypeSymbol,
				"OnValidate",
				model.PropertyNames.Length
			)
		)
			return;

		var validateParams = string.Join(
			", ",
			model.PropertyTypeNames.Zip(
				model.PropertyNames,
				static (type, name) => $"{type} {ValueObjectSymbolInspector.ToCamelCase(name)}"
			)
		);
		var validateReadOnly =
			model.TypeSymbol.TypeKind == TypeKind.Struct
			&& ValueObjectSymbolInspector.IsComplexHookReadOnly(
				model.TypeSymbol,
				"OnValidate",
				model.PropertyNames.Length
			);
		var readOnlyPrefix = validateReadOnly ? "readonly " : string.Empty;
		sb.AppendLine(
			$"{indent}	[global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Performance\", \"CA1822:Mark members as static\")]"
		);
		sb.AppendLine($"{indent}	{readOnlyPrefix}partial void OnValidate({validateParams});");
		sb.AppendLine();
	}

	static void EmitHydrateFactory(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (model.HydrateExists)
			return;

		var hydrateParams = string.Join(
			", ",
			model.PropertyTypeNames.Zip(
				model.PropertyNames,
				static (type, name) => $"{type} {ValueObjectSymbolInspector.ToCamelCase(name)}"
			)
		);
		var hydrateArgs = string.Join(
			", ",
			model.PropertyNames.Select(ValueObjectSymbolInspector.ToCamelCase)
		);
		sb.AppendLine(
			$@"{indent}	public static {model.TypeName} Hydrate({hydrateParams})
{indent}	{{
{indent}		return new({hydrateArgs});
{indent}	}}"
		);
		sb.AppendLine();
	}

	static void EmitEmpty(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (
			model.Options.GenerateEmpty
			&& !ValueObjectSymbolInspector.HasMemberWithName(model.TypeSymbol, "Empty")
		)
		{
			var emptyArgs = string.Join(
				", ",
				model.Properties.Select(static property =>
					ValueObjectSymbolInspector.GetEmptyValueExpression(property.Type)
				)
			);
			sb.AppendLine(
				$"{indent}	public static {model.TypeName} Empty => Hydrate({emptyArgs});"
			);
			sb.AppendLine();
		}
	}

	static void EmitConstructor(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (model.CtorExists || model.PropertyNames.Length == 0)
			return;

		var ctorParams = string.Join(
			", ",
			model.PropertyTypeNames.Zip(
				model.PropertyNames,
				static (type, name) => $"{type} {ValueObjectSymbolInspector.ToCamelCase(name)}"
			)
		);
		sb.AppendLine();
		sb.AppendLine(
			$@"{indent}	private {model.TypeModel.Name}({ctorParams})
{indent}	{{"
		);
		foreach (var propertyName in model.PropertyNames)
			sb.AppendLine(
				$"{indent}		{propertyName} = {ValueObjectSymbolInspector.ToCamelCase(propertyName)};"
			);
		sb.AppendLine($"{indent}	}}");
	}

	static void EmitEfConstructor(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (
			!model.Options.GenerateConstructor
			|| model.ParameterlessCtorExists
			|| !ValueObjectSymbolInspector.TryGetEfConstructorArguments(
				model.TypeSymbol,
				model.Properties,
				out var efCtorArguments
			)
		)
			return;

		var efCtorAccessibility =
			model.TypeSymbol.TypeKind == TypeKind.Struct ? "public" : "private";
		sb.AppendLine();
		sb.AppendLine($"{indent}	/// <summary>");
		sb.AppendLine($"{indent}	/// Parameterless constructor for EF Core deserialization.");
		sb.AppendLine(
			$"{indent}	/// This constructor is required to work around EF Core's ConstructorBindingConvention,"
		);
		sb.AppendLine(
			$"{indent}	/// which cannot bind complex type parameters during JSON deserialization."
		);
		sb.AppendLine(
			$"{indent}	/// EF Core uses this parameterless constructor to instantiate the value object,"
		);
		sb.AppendLine($"{indent}	/// then sets properties directly from the JSON payload.");
		sb.AppendLine($"{indent}	/// </summary>");
		sb.AppendLine(
			$@"{indent}	{efCtorAccessibility} {model.TypeModel.Name}() : this({efCtorArguments})
{indent}	{{"
		);
		sb.AppendLine($"{indent}	}}");
	}

	static void EmitEquality(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (!model.EqualsSelfExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				model.IsReferenceType
					? $@"{indent}	public bool Equals({model.TypeName} other)
{indent}	{{
{indent}		if (other is null)
{indent}			return false;"
					: $"{indent}	public bool Equals({model.TypeName} other)\n{indent}	{{"
			);
			for (var i = 0; i < model.Properties.Length; i++)
			{
				sb.AppendLine(
					$"{indent}		if (!global::System.Collections.Generic.EqualityComparer<{model.PropertyTypeNames[i]}>.Default.Equals({model.PropertyNames[i]}, other.{model.PropertyNames[i]}))"
				);
				sb.AppendLine($"{indent}			return false;");
			}

			sb.AppendLine($"{indent}		return true;");
			sb.AppendLine($"{indent}	}}");
		}

		if (!model.EqualsObjectExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				$@"{indent}	public override bool Equals(object? obj) =>
{indent}		obj is {model.TypeName} other && Equals(other);"
			);
		}

		if (!model.GetHashCodeExists)
		{
			sb.AppendLine();
			sb.AppendLine($"{indent}	public override int GetHashCode()");
			sb.AppendLine($"{indent}	{{");
			sb.AppendLine($"{indent}		global::System.HashCode hash = new();");
			for (var i = 0; i < model.PropertyNames.Length; i++)
				sb.AppendLine($"{indent}		hash.Add({model.PropertyNames[i]});");
			sb.AppendLine($"{indent}		return hash.ToHashCode();");
			sb.AppendLine($"{indent}	}}");
		}
	}

	static void EmitOperators(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (!model.EqualityOperatorExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				model.IsReferenceType
					? $"{indent}	public static bool operator ==({model.TypeName} left, {model.TypeName} right) =>\n{indent}		left is null ? right is null : left.Equals(right);"
					: $"{indent}	public static bool operator ==({model.TypeName} left, {model.TypeName} right) =>\n{indent}		left.Equals(right);"
			);
		}

		if (!model.InequalityOperatorExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				$"{indent}	public static bool operator !=({model.TypeName} left, {model.TypeName} right) =>\n{indent}		!(left == right);"
			);
		}
	}

	static void EmitComparison(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (!model.Options.GenerateComparable)
			return;

		if (!model.CompareToSelfExists)
		{
			sb.AppendLine(
				$@"{indent}	public int CompareTo({model.CompareToSelfParameterTypeName} other)
{indent}	{{"
			);
			if (model.TypeSymbol.TypeKind == TypeKind.Class)
			{
				sb.AppendLine(
					$@"{indent}		if (other is null)
{indent}			return 1;"
				);
			}

			for (var i = 0; i < model.Properties.Length; i++)
			{
				var prop = model.Properties[i];
				var propTypeName = model.PropertyTypeNames[i];
				sb.AppendLine(
					$@"{indent}		var compare{prop.Name} = global::System.Collections.Generic.Comparer<{propTypeName}>.Default.Compare({prop.Name}, other.{prop.Name});
{indent}		if (compare{prop.Name} != 0)
{indent}			return compare{prop.Name};"
				);
			}

			sb.AppendLine(
				$@"{indent}		return 0;
{indent}	}}"
			);
		}

		if (!model.CompareToObjectExists)
		{
			sb.AppendLine(
				$@"{indent}	public int CompareTo(object? obj)
{indent}	{{
{indent}		if (obj is null)
{indent}			return 1;
{indent}		if (obj is {model.TypeName} otherValueObject)
{indent}			return CompareTo(otherValueObject);
{indent}		throw new global::System.ArgumentException($""Object must be of type {{nameof({model.TypeModel.Name})}}."", nameof(obj));
{indent}	}}"
			);
		}

		if (model.Options.GenerateComparisonOperators)
		{
			ValueObjectEmitterHelpers.EmitRelationalOperators(
				sb,
				indent,
				model.TypeSymbol,
				model.TypeName,
				model.TypeName,
				"CompareTo(right)"
			);
		}
	}

	static void EmitJsonConverter(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		if (!model.Options.GenerateJsonConverter)
			return;

		var modelTypeName = $"{model.TypeModel.Name}JsonModel";
		var toModelAssignments = string.Join(
			", ",
			model.PropertyNames.Select(static name => $"{name} = value.{name}")
		);
		var hydrateArgs = string.Join(
			", ",
			model.PropertyNames.Select(static name => $"model.{name}")
		);

		sb.AppendLine();
		sb.AppendLine(
			$@"{indent}	sealed class {model.TypeModel.Name}JsonConverter : global::System.Text.Json.Serialization.JsonConverter<{model.TypeName}>
{indent}	{{
{indent}		public override {model.TypeName} Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
{indent}		{{
{indent}			var model = global::System.Text.Json.JsonSerializer.Deserialize<{modelTypeName}>(ref reader, options);
{indent}			if (model is null)
{indent}				throw new global::System.Text.Json.JsonException(""Unable to deserialize {model.TypeModel.Name}."");
{indent}			return {model.HydrateFactoryName}({hydrateArgs});
{indent}		}}

{indent}		public override void Write(global::System.Text.Json.Utf8JsonWriter writer, {model.TypeName} value, global::System.Text.Json.JsonSerializerOptions options)
{indent}		{{
{indent}			var model = new {modelTypeName} {{ {toModelAssignments} }};
{indent}			global::System.Text.Json.JsonSerializer.Serialize(writer, model, options);
{indent}		}}
{indent}	}}

{indent}	sealed class {modelTypeName}
{indent}	{{"
		);

		for (var i = 0; i < model.Properties.Length; i++)
		{
			sb.AppendLine(
				$"{indent}		public {model.PropertyTypeNames[i]} {model.PropertyNames[i]} {{ get; set; }} = default!;"
			);
		}

		sb.AppendLine($"{indent}	}}");
	}

	static void EmitFooter(StringBuilder sb, ComplexValueObjectModel model, string indent)
	{
		sb.AppendLine($"{indent}}}");
		if (model.TypeModel.Namespace is not null)
			sb.AppendLine("}");
	}
}
