using System.Text;
using Microsoft.CodeAnalysis;

namespace Purview.EventSourcing.SourceGenerator.ValueObject;

static class ScalarValueObjectEmitter
{
	public static string Emit(ScalarValueObjectModel model)
	{
		StringBuilder sb = new();
		var indent = model.TypeModel.Namespace is null ? string.Empty : "	";

		EmitHeader(sb, model, indent);
		EmitHookDeclarations(sb, model, indent);
		EmitFactories(sb, model, indent);
		EmitEmpty(sb, model, indent);
		EmitTryCreate(sb, model, indent);
		EmitComparison(sb, model, indent);
		EmitConstructor(sb, model, indent);
		EmitEnumProperties(sb, model, indent);
		EmitEquality(sb, model, indent);
		EmitOperators(sb, model, indent);
		EmitConversions(sb, model, indent);
		EmitToString(sb, model, indent);
		EmitJsonConverter(sb, model, indent);
		EmitFooter(sb, model, indent);

		return sb.ToString();
	}

	static void EmitHeader(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		if (model.TypeModel.Namespace is not null)
		{
			sb.AppendLine($"namespace {model.TypeModel.Namespace}");
			sb.AppendLine("{");
		}

		if (model.Options.GenerateJsonConverter && !model.HasJsonConverterAttribute)
			sb.AppendLine(
				$"{indent}[global::System.Text.Json.Serialization.JsonConverter(typeof({model.TypeModel.Name}JsonConverter))]"
			);

		var scalarSelfEquatableInterface =
			model.TypeSymbol.TypeKind == TypeKind.Struct
			&& !ValueObjectSymbolInspector.ImplementsSelfEquatable(model.TypeSymbol)
				? $", global::System.IEquatable<{model.TypeName}>"
				: string.Empty;
		sb.AppendLine(
			$"{indent}{model.TypeModel.DeclarationPrefix} : global::Purview.EventSourcing.ValueObjects.IScalarValueObject<{model.TypeName}, {model.ScalarTypeName}>{scalarSelfEquatableInterface}, global::System.IComparable<{model.TypeName}>, global::System.IComparable<{model.ScalarTypeName}>, global::System.IComparable"
		);
		sb.AppendLine($"{indent}{{");
	}

	static void EmitHookDeclarations(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (model.DeclareOnNormalize)
			sb.AppendLine(
				$"{indent}	static partial void OnNormalize(ref {model.ScalarTypeName} value);"
			);
		if (model.DeclareOnValidate)
			sb.AppendLine(
				$"{indent}	static partial void OnValidate({model.ScalarTypeName} value);"
			);
		if (model.DeclareOnNormalize || model.DeclareOnValidate)
			sb.AppendLine();
	}

	static void EmitFactories(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (!model.CreateExists)
		{
			sb.AppendLine(
				$@"{indent}	public static {model.TypeName} Create({model.ScalarTypeName} value)
{indent}	{{
{indent}		OnNormalize(ref value);
{indent}		OnValidate(value);
{indent}		return new(value);
{indent}	}}"
			);
			sb.AppendLine();
		}

		if (!model.HydrateExists)
		{
			sb.AppendLine(
				$@"{indent}	public static {model.TypeName} Hydrate({model.ScalarTypeName} value)
{indent}	{{
{indent}		return new(value);
{indent}	}}"
			);
			sb.AppendLine();
		}
	}

	static void EmitEmpty(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (
			model.Options.GenerateEmpty
			&& !ValueObjectSymbolInspector.HasMemberWithName(model.TypeSymbol, "Empty")
		)
		{
			sb.AppendLine(
				$"{indent}	public static {model.TypeName} Empty => Hydrate({ValueObjectSymbolInspector.GetEmptyValueExpression(model.ScalarProperty.Type)});"
			);
			sb.AppendLine();
		}
	}

	static void EmitTryCreate(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (!model.TryCreateExists)
		{
			sb.AppendLine(
				$@"{indent}	public static bool TryCreate({model.ScalarTypeName} value, out {model.TypeName} result)
{indent}	{{
{indent}		try
{indent}		{{
{indent}			result = Create(value);
{indent}			return true;
{indent}		}}
{indent}		catch (global::System.ArgumentException)
{indent}		{{
{indent}			result = default!;
{indent}			return false;
{indent}		}}
{indent}	}}"
			);
			sb.AppendLine();
		}
	}

	static void EmitComparison(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (!model.Options.GenerateComparable)
			return;

		if (!model.CompareToSelfExists)
		{
			sb.AppendLine(
				model.TypeSymbol.TypeKind == TypeKind.Class
					? $@"{indent}	public int CompareTo({model.CompareToSelfParameterTypeName} other)
{indent}	{{
{indent}		if (other is null)
{indent}			return 1;
{indent}		return CompareTo(other.{model.ScalarPropertyName});
{indent}	}}"
					: $"{indent}	public int CompareTo({model.CompareToSelfParameterTypeName} other) => CompareTo(other.{model.ScalarPropertyName});"
			);
		}

		if (!model.CompareToPrimitiveExists)
		{
			sb.AppendLine(
				$"{indent}	public int CompareTo({model.CompareParameterTypeName} other) => global::System.Collections.Generic.Comparer<{model.ScalarTypeName}>.Default.Compare({model.ScalarPropertyName}, other);"
			);
		}

		if (!model.CompareToObjectExists)
		{
			sb.AppendLine(
				$@"{indent}	public int CompareTo(object? obj)
{indent}	{{
{indent}		if (obj is null)
{indent}			return 1;
{indent}		if (obj is {model.TypeName} otherValueObject)
{indent}			return CompareTo(otherValueObject);
{indent}		if (obj is {model.ScalarTypeName} primitive)
{indent}			return CompareTo(primitive);
{indent}		throw new global::System.ArgumentException($""Object must be of type {{nameof({model.TypeModel.Name})}} or {model.ScalarTypeName}."", nameof(obj));
{indent}	}}"
			);
		}

		if (model.Options.GenerateComparisonOperators)
		{
			ValueObjectEmitterHelpers.EmitRelationalOperators(
				sb,
				indent,
				model.TypeSymbol,
				model.TypeName,
				model.TypeName,
				"CompareTo(right)"
			);

			var scalarAndSelfAreSameType = SymbolEqualityComparer.Default.Equals(
				model.ScalarProperty.Type,
				model.TypeSymbol
			);
			if (!scalarAndSelfAreSameType)
			{
				ValueObjectEmitterHelpers.EmitRelationalOperators(
					sb,
					indent,
					model.TypeSymbol,
					model.TypeName,
					model.ScalarTypeName,
					"CompareTo(right)"
				);
			}
		}

		sb.AppendLine();
	}

	static void EmitConstructor(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (!model.CtorExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				$"{indent}	private {model.TypeModel.Name}({model.ScalarTypeName} value) => {model.ScalarPropertyName} = value;"
			);
		}
	}

	static void EmitEnumProperties(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (!model.EnumPropertiesEnabled)
			return;

		foreach (
			var enumField in ValueObjectSymbolInspector.GetEnumFields(model.ScalarProperty.Type)
		)
		{
			if (ValueObjectSymbolInspector.HasMemberWithName(model.TypeSymbol, enumField.Name))
				continue;

			sb.AppendLine();
			sb.AppendLine(
				$"{indent}	public static {model.TypeName} {enumField.Name} => Hydrate({model.ScalarTypeName}.{enumField.Name});"
			);
		}
	}

	static void EmitEquality(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (!model.EqualsSelfExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				model.IsReferenceType
					? $"{indent}	public bool Equals({model.TypeName} other) => other is not null && global::System.Collections.Generic.EqualityComparer<{model.ScalarTypeName}>.Default.Equals({model.ScalarPropertyName}, other.{model.ScalarPropertyName});"
					: $"{indent}	public bool Equals({model.TypeName} other) => global::System.Collections.Generic.EqualityComparer<{model.ScalarTypeName}>.Default.Equals({model.ScalarPropertyName}, other.{model.ScalarPropertyName});"
			);
		}

		if (!model.EqualsPrimitiveExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				$"{indent}	public bool Equals({model.ScalarTypeName} other) => global::System.Collections.Generic.EqualityComparer<{model.ScalarTypeName}>.Default.Equals({model.ScalarPropertyName}, other);"
			);
		}

		if (!model.EqualsObjectExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				$@"{indent}	public override bool Equals(object? obj) =>
{indent}		obj is {model.TypeName} other ? Equals(other) : obj is {model.ScalarTypeName} primitive && Equals(primitive);"
			);
		}

		if (!model.GetHashCodeExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				$"{indent}	public override int GetHashCode() => global::System.Collections.Generic.EqualityComparer<{model.ScalarTypeName}>.Default.GetHashCode({model.ScalarPropertyName});"
			);
		}
	}

	static void EmitOperators(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (!model.SameTypeEqualityOperatorExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				model.IsReferenceType
					? $"{indent}	public static bool operator ==({model.TypeName} left, {model.TypeName} right) =>\n{indent}		left is null ? right is null : left.Equals(right);"
					: $"{indent}	public static bool operator ==({model.TypeName} left, {model.TypeName} right) =>\n{indent}		left.Equals(right);"
			);
		}

		if (!model.SameTypeInequalityOperatorExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				$"{indent}	public static bool operator !=({model.TypeName} left, {model.TypeName} right) =>\n{indent}		!(left == right);"
			);
		}

		if (!model.PrimitiveEqualityOperatorExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				model.IsReferenceType
					? $"{indent}	public static bool operator ==({model.TypeName} left, {model.ScalarTypeName} right) =>\n{indent}		left is null ? false : left.Equals(right);"
					: $"{indent}	public static bool operator ==({model.TypeName} left, {model.ScalarTypeName} right) =>\n{indent}		left.Equals(right);"
			);
		}

		if (!model.PrimitiveInequalityOperatorExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				$"{indent}	public static bool operator !=({model.TypeName} left, {model.ScalarTypeName} right) =>\n{indent}		!(left == right);"
			);
		}

		if (!model.ReversePrimitiveEqualityOperatorExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				model.IsReferenceType
					? $"{indent}	public static bool operator ==({model.ScalarTypeName} left, {model.TypeName} right) =>\n{indent}		right is not null && right.Equals(left);"
					: $"{indent}	public static bool operator ==({model.ScalarTypeName} left, {model.TypeName} right) =>\n{indent}		right.Equals(left);"
			);
		}

		if (!model.ReversePrimitiveInequalityOperatorExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				$"{indent}	public static bool operator !=({model.ScalarTypeName} left, {model.TypeName} right) =>\n{indent}		!(left == right);"
			);
		}
	}

	static void EmitConversions(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (
			model.Options.GenerateImplicitToPrimitive
			&& !ValueObjectSymbolInspector.HasConversionOperator(
				model.TypeSymbol,
				model.ScalarProperty.Type,
				false
			)
		)
		{
			sb.AppendLine(
				$"{indent}	public static implicit operator {model.ScalarTypeName}({model.TypeName} valueObject) => valueObject.{model.ScalarPropertyName};"
			);
		}

		if (
			model.Options.GenerateImplicitFromPrimitive
			&& !ValueObjectSymbolInspector.HasContextualCreateOverload(
				model.TypeSymbol,
				model.ScalarProperty.Type
			)
			&& !ValueObjectSymbolInspector.HasConversionOperator(
				model.TypeSymbol,
				model.ScalarProperty.Type,
				true
			)
		)
		{
			sb.AppendLine(
				$"{indent}	public static implicit operator {model.TypeName}({model.ScalarTypeName} value) => Create(value);"
			);
		}
	}

	static void EmitToString(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (!model.ToStringExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				$"{indent}	public override string ToString() => {model.ScalarPropertyName}.ToString() ?? string.Empty;"
			);
		}
	}

	static void EmitJsonConverter(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (!model.Options.GenerateJsonConverter)
			return;

		sb.AppendLine();
		sb.AppendLine(
			$@"{indent}	sealed class {model.TypeModel.Name}JsonConverter : global::System.Text.Json.Serialization.JsonConverter<{model.TypeName}>
{indent}	{{
{indent}		public override {model.TypeName} Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
{indent}		{{
{indent}			var value = global::System.Text.Json.JsonSerializer.Deserialize<{model.ScalarTypeName}>(ref reader, options);
{(model.ScalarCanBeNull ? $"{indent}			if (value is null)\n{indent}				throw new global::System.Text.Json.JsonException(\"{model.TypeModel.Name} cannot be null.\");\n" : string.Empty)}{indent}			return {(model.Options.DeserializationMode == ValueObjectSymbolInspector.StrictModeName ? "Create" : "Hydrate")}(value);
{indent}		}}

{indent}		public override void Write(global::System.Text.Json.Utf8JsonWriter writer, {model.TypeName} value, global::System.Text.Json.JsonSerializerOptions options) =>
{indent}			global::System.Text.Json.JsonSerializer.Serialize(writer, value.{model.ScalarPropertyName}, options);
{indent}	}}"
		);
	}

	static void EmitFooter(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		sb.AppendLine($"{indent}}}");
		if (model.TypeModel.Namespace is not null)
			sb.AppendLine("}");
	}
}
