using System.Text;
using Microsoft.CodeAnalysis;

namespace Purview.EventSourcing.SourceGenerator.ValueObject;

static partial class ScalarValueObjectEmitter
{
	public static string Emit(ScalarValueObjectModel model)
	{
		StringBuilder sb = new();
		var indent = model.TypeModel.Namespace is null ? string.Empty : "	";

		EmitHeader(sb, model, indent);
		EmitHookDeclarations(sb, model, indent);
		EmitFactories(sb, model, indent);
		EmitEmpty(sb, model, indent);
		EmitTryCreate(sb, model, indent);
		EmitComparison(sb, model, indent);
		EmitConstructor(sb, model, indent);
		EmitEnumProperties(sb, model, indent);
		EmitEquality(sb, model, indent);
		EmitOperators(sb, model, indent);
		EmitConversions(sb, model, indent);
		EmitToString(sb, model, indent);
		EmitJsonConverter(sb, model, indent);
		EmitFooter(sb, model, indent);

		return sb.ToString();
	}

	static void EmitHeader(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		if (model.TypeModel.Namespace is not null)
		{
			sb.AppendLine($"namespace {model.TypeModel.Namespace}");
			sb.AppendLine("{");
		}

		if (model.Options.GenerateJsonConverter && !model.HasJsonConverterAttribute)
			sb.AppendLine(
				$"{indent}[global::System.Text.Json.Serialization.JsonConverter(typeof({model.TypeModel.Name}JsonConverter))]"
			);

		var scalarSelfEquatableInterface =
			model.TypeSymbol.TypeKind == TypeKind.Struct
			&& !ValueObjectSymbolInspector.ImplementsSelfEquatable(model.TypeSymbol)
				? $", global::System.IEquatable<{model.TypeName}>"
				: string.Empty;
		sb.AppendLine(
			$"{indent}{model.TypeModel.DeclarationPrefix} : global::Purview.EventSourcing.ValueObjects.IScalarValueObject<{model.TypeName}, {model.ScalarTypeName}>{scalarSelfEquatableInterface}, global::System.IComparable<{model.TypeName}>, global::System.IComparable<{model.ScalarTypeName}>, global::System.IComparable"
		);
		sb.AppendLine($"{indent}{{");
	}

	static void EmitHookDeclarations(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (model.DeclareOnNormalize)
			sb.AppendLine(
				$"{indent}	static partial void OnNormalize(ref {model.ScalarTypeName} value);"
			);
		if (model.DeclareOnValidate)
			sb.AppendLine(
				$"{indent}	static partial void OnValidate({model.ScalarTypeName} value);"
			);
		if (model.DeclareOnNormalize || model.DeclareOnValidate)
			sb.AppendLine();
	}

	static void EmitFactories(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (!model.CreateExists)
		{
			sb.AppendLine(
				$@"{indent}	public static {model.TypeName} Create({model.ScalarTypeName} value)
{indent}	{{
{indent}		OnNormalize(ref value);
{indent}		OnValidate(value);
{indent}		return new(value);
{indent}	}}"
			);
			sb.AppendLine();
		}

		if (!model.HydrateExists)
		{
			sb.AppendLine(
				$@"{indent}	public static {model.TypeName} Hydrate({model.ScalarTypeName} value)
{indent}	{{
{indent}		return new(value);
{indent}	}}"
			);
			sb.AppendLine();
		}
	}

	static void EmitEmpty(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (
			model.Options.GenerateEmpty
			&& !ValueObjectSymbolInspector.HasMemberWithName(model.TypeSymbol, "Empty")
		)
		{
			sb.AppendLine(
				$"{indent}	public static {model.TypeName} Empty => Hydrate({ValueObjectSymbolInspector.GetEmptyValueExpression(model.ScalarProperty.Type)});"
			);
			sb.AppendLine();
		}
	}

	static void EmitTryCreate(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (!model.TryCreateExists)
		{
			sb.AppendLine(
				$@"{indent}	public static bool TryCreate({model.ScalarTypeName} value, out {model.TypeName} result)
{indent}	{{
{indent}		try
{indent}		{{
{indent}			result = Create(value);
{indent}			return true;
{indent}		}}
{indent}		catch (global::System.ArgumentException)
{indent}		{{
{indent}			result = default!;
{indent}			return false;
{indent}		}}
{indent}	}}"
			);
			sb.AppendLine();
		}
	}

	static void EmitConstructor(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (!model.CtorExists)
		{
			sb.AppendLine();
			sb.AppendLine(
				$"{indent}	private {model.TypeModel.Name}({model.ScalarTypeName} value) => {model.ScalarPropertyName} = value;"
			);
		}
	}

	static void EmitEnumProperties(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		if (!model.EnumPropertiesEnabled)
			return;

		foreach (
			var enumField in ValueObjectSymbolInspector.GetEnumFields(model.ScalarProperty.Type)
		)
		{
			if (ValueObjectSymbolInspector.HasMemberWithName(model.TypeSymbol, enumField.Name))
				continue;

			sb.AppendLine();
			sb.AppendLine(
				$"{indent}	public static {model.TypeName} {enumField.Name} => Hydrate({model.ScalarTypeName}.{enumField.Name});"
			);
		}
	}

	static void EmitFooter(StringBuilder sb, ScalarValueObjectModel model, string indent)
	{
		sb.AppendLine($"{indent}}}");
		if (model.TypeModel.Namespace is not null)
			sb.AppendLine("}");
	}
}
