using Microsoft.CodeAnalysis.Text;
using Purview.EventSourcing.SourceGenerator.Generators;

namespace Purview.EventSourcing.SourceGenerator.ValueObject;

static class ValueObjectsAttributeEmitter
{
	public static IEnumerable<(string HintName, SourceText Source)> EmitAttributes()
	{
		yield return (nameof(ValueObjectDefaultsAttribute) + ".g.cs", ValueObjectDefaultsAttribute());
	}

	static SourceText ValueObjectDefaultsAttribute()
	{
		var writer = GetCodeWriter();

		writer
			.XmlSummary(
				"Specifies assembly-level defaults for value object code generation.",
				$"These defaults can be overridden on individual {XmlSee(TypeLibrary.Attributes.ValueObjectAttributeFullTypeName)} attributes."
			)
			.WriteAttributeClass(
				new(TypeLibrary.Attributes.ValueObjectDefaultsAttribute),
				AttributeTargets.Assembly,
				bodyWriter =>
				{
					bodyWriter.WriteConstructor(
						new(TypeLibrary.Attributes.ValueObjectDefaultsAttribute, TypeDeclarationAccessibility.Public)
						{
							Parameters = [new("generateConstructor", PurviewTypeLibrary.System.Boolean) { }],
						},
						static ctor => ctor.WriteAssignment("GenerateConstructor", "generateConstructor")
					);

					bodyWriter
						.XmlSummary(
							"Gets or sets whether parameterless constructors should be generated for value objects.",
							"When true, generates a private parameterless constructor for EF Core compatibility.",
							$"Individual {XmlSee(TypeLibrary.Attributes.ValueObjectAttributeFullTypeName)} attributes can override this setting.",
							"Default: true"
						)
						.WriteProperty(
							new(
								"GenerateConstructor",
								PurviewTypeLibrary.System.Boolean,
								TypeDeclarationAccessibility.Public
							)
							{
								Initializer = "true",
							}
						);
				}
			);

		return writer;
	}

	static CodeWriter GetCodeWriter()
	{
		var writer = new CodeWriter(GenerationSettings.Create<ValueObjectSourceGenerator>());

		return writer.WriteAutoGeneratedHeader();
	}
}
