<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="..\..\src\Admin.Abstractions\Admin.Abstractions.csproj" />
		<ProjectReference Include="..\..\src\Admin.Security\Admin.Security.csproj" />
		<ProjectReference Include="..\..\src\Admin.API\Admin.API.csproj" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
</Project>
