<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Admin.Abstractions\Admin.Abstractions.csproj" />
		<ProjectReference Include="..\..\src\Admin.Security\Admin.Security.csproj" />
		<ProjectReference Include="..\..\src\Admin.API\Admin.API.csproj" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="TUnit.Core" />
	</ItemGroup>
</Project>
