// <auto-generated />

#nullable enable

namespace Purview.EventSourcing.Aggregates;

/// <summary>
/// Marks a parameter as a specific property on the aggregate for source generation.
/// </summary>
{{CodeGen}}
[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
sealed class AggregatePropertyAttribute : global::System.Attribute
{
	/// <summary>
	/// Initializes a new instance of the <see cref="AggregatePropertyAttribute"/> class with the specified property name.
	/// </summary>
	/// <param name="propertyName">The name of the aggregate property that this parameter corresponds to.</param>
	/// <exception cref="global::System.ArgumentException">Thrown when the property name is null or whitespace.</exception>
	public AggregatePropertyAttribute(string propertyName)
	{
		if (string.IsNullOrWhiteSpace(propertyName))
			throw new global::System.ArgumentException("Property name cannot be null or whitespace.", nameof(propertyName));

		PropertyName = propertyName;
	}

	/// <summary>
	/// Specifies the name of the aggregate property that this parameter corresponds to.
	/// </summary>
	public string PropertyName { get; }
}
