// <auto-generated />

#nullable enable

namespace Purview.EventSourcing.Aggregates;

/// <summary>
/// Sets default source-generation options for all <see cref="GenerateAggregateAttribute"/> aggregates in an assembly.
/// Aggregate-level options override these defaults.
/// </summary>
{{CodeGen}}
[global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false, Inherited = false)]
sealed class GenerateAggregateDefaultsAttribute : global::System.Attribute
{
	/// <summary>
	/// Appends a suffix to generated event type names when no explicit <see cref="GenerateAggregateEventAttribute.EventName"/> is provided.
	/// Defaults to <c>Event</c>.
	/// </summary>
	public string? EventSuffix { get; set; } = "Event";
}
