// <auto-generated />

#nullable enable

namespace Purview.EventSourcing.Aggregates;

/// <summary>
/// Specifies the default base class for all aggregates in the assembly.
/// The specified type must inherit from AggregateBase.
/// This attribute can be applied at the assembly level to set a global default.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
public sealed class GenerateAggregateDefaultBaseAttribute : global::System.Attribute
{
	/// <summary>
	/// The default base class type for aggregates. Must inherit from AggregateBase.
	/// If null, AggregateBase is used as the default.
	/// </summary>
	public global::System.Type? BaseType { get; }

	public GenerateAggregateDefaultBaseAttribute(global::System.Type? baseType = null)
	{
		BaseType = baseType;
	}
}
