// <auto-generated />

#nullable enable

namespace Purview.EventSourcing.Aggregates;

/// <summary>
/// Marks a partial class extending <c>AggregateBase</c> for source generation.
/// The generator will create the <c>RegisterEvents()</c> override and
/// event classes based on methods decorated with <see cref="GenerateAggregateEventAttribute"/>.
/// </summary>
{{CodeGen}}
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
sealed class GenerateAggregateAttribute : global::System.Attribute
{
	/// <summary>
	/// Overrides the generated event namespace for all event methods on this aggregate.
	/// When not set, namespaces default to:
	/// <c>{AggregateNamespace}.{AggregateNameWithoutAggregateSuffix}</c>.
	/// </summary>
	public string? EventNamespace { get; set; }

	/// <summary>
	/// Appends a suffix to generated event type names when no explicit
	/// <see cref="GenerateAggregateEventAttribute.EventName"/> is provided.
	/// Overrides <see cref="GenerateAggregateDefaultsAttribute.EventSuffix"/> for this aggregate.
	/// Defaults to <c>Event</c>.
	/// </summary>
	public string? EventSuffix { get; set; } = "Event";
}
