// <auto-generated />

#nullable enable

namespace Purview.EventSourcing.Aggregates;

/// <summary>
/// Indicates the type of collection operation that a method represents when generating an event for a collection property.
/// </summary>
{{NonClassCodeGen}}
enum CollectionEventOperation
{
	Auto = 0,
	Add = 1,
	Remove = 2,
}

/// <summary>
/// Marks a method on a <see cref="GenerateAggregateCollectionEventAttribute"/>-decorated class
/// as a command that should have an event class and registration generated.
/// <para>
/// The method parameters become the event's properties. The generator creates:
/// <list type="bullet">
///   <item>An event class named from the method using a deterministic past-tense convention, such as <c>NameChanged</c> or <c>CustomerRegistered</c></item>
///   <item>A <c>Register&lt;{EventName}&gt;(Apply)</c> call in <c>RegisterEvents()</c></item>
///   <item>An <c>Apply({EventName})</c> method that sets matching properties</item>
///   <item>The method body calls <c>RecordAndApply(new {EventName} { ... })</c></item>
/// </list>
/// </para>
/// </summary>
/// <remarks>
/// Use <see cref="Version"/> to declare the schema version of the generated event class.
/// Increment this value whenever the event's properties change in a breaking way.
/// The generated event class will override <c>SchemaVersion</c> to return this value.
/// <para>
/// Use <see cref="EventName"/> and <see cref="EventNamespace"/> to override the default generated
/// event type name and namespace for a specific method.
/// </para>
/// </remarks>
{{CodeGen}}
[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
sealed class GenerateAggregateCollectionEventAttribute : global::System.Attribute
{
	public GenerateAggregateCollectionEventAttribute(string propertyName)
	{
		if (string.IsNullOrWhiteSpace(propertyName))
			throw new global::System.ArgumentException("Property name cannot be null or whitespace.", nameof(propertyName));

		PropertyName = propertyName;
	}

	/// <summary>
	/// The schema version of the generated event class. Defaults to 1.
	/// Increment when the event's properties change in a <b>breaking</b> way.
	/// </summary>
	public int Version { get; set; } = 1;

	/// <summary>
	/// Overrides the generated event type name for this method.
	/// Defaults to a deterministic past-tense event name inferred from the method name.
	/// If not set, <see cref="GenerateAggregateAttribute.EventSuffix"/> and
	/// <see cref="GenerateAggregateDefaultsAttribute.EventSuffix"/> may append a suffix.
	/// </summary>
	public string? EventName { get; set; }

	/// <summary>
	/// Overrides the generated event namespace for this method.
	/// Defaults to <c>{AggregateNamespace}.{AggregateNameWithoutAggregateSuffix}</c>
	/// unless overridden at aggregate level.
	/// </summary>
	public string? EventNamespace { get; set; }

	/// <summary>
	/// The property name of the collection property on the aggregate that this method modifies.
	/// </summary>
	public string PropertyName { get; }

	/// <summary>
	/// Overrides collection mutation behavior. By default (<see cref="CollectionEventOperation.Auto"/>),
	/// methods starting with <c>Add</c> are treated as add mutations and methods starting with
	/// <c>Remove</c> or <c>Delete</c> are treated as remove mutations.
	/// </summary>
	public CollectionEventOperation Operation { get; set; } = CollectionEventOperation.Auto;

	/// <summary>
	/// Indicates whether the event's apply method should be generated manually instead of automatically.
	///
	/// If Manual is <langword>true</langword>, the generator will not create an <c>Apply({EventName})</c> method for this event.
	///
	/// An <c>Apply({EventName})</c> method must be implemented manually in the aggregate class to handle the event and update the aggregate's state, or
	/// the source generator will create an error indicating that the apply method is missing.
	/// </summary>
	public bool Manual { get; set; }
}
