// <auto-generated />

#nullable enable

namespace Purview.EventSourcing.Aggregates;

/// <summary>
/// Marks a parameter as metadata for the aggregate, indicating whether it should be stored.
/// </summary>
{{CodeGen}}
[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
sealed class MetadataAttribute : global::System.Attribute
{
	/// <summary>
	/// Initializes a new instance of the <see cref="MetadataAttribute"/> class, determining
	/// if the parameter should be stored on the generated event or not.
	/// </summary>
	/// <param name="store">Indicates whether the metadata should be stored.</param>
	public MetadataAttribute(bool store = true)
	{
		Store = store;
	}

	/// <summary>
	/// Indicates whether the metadata should be stored on the generated event or not.
	/// </summary>
	public bool Store { get; }
}
