<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!-- Temporarily disable the complexity rule until we can refactor the code -->
		<NoWarn>$(NoWarn);CA1506;</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Samples.Web\Samples.Web.csproj" />
		<!-- Direct reference required when not used via a NuGet package -->
		<ProjectReference
			Include="..\..\src\SourceGenerator\SourceGenerator.csproj"
			OutputItemType="Analyzer"
			ReferenceOutputAssembly="false"
			PrivateAssets="all"
		/>
	</ItemGroup>
</Project>
