<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<IsRoslynComponent>true</IsRoslynComponent>
		<AssemblyName>Purview.EventSourcing.SourceGeneration</AssemblyName>
		<!--<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>-->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
		<PackageReference Include="Purview.SourceGeneratorFramework" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
		<AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Purview.EventSourcing.SourceGenerator.Common" />
		<Using Include="Purview.EventSourcing.SourceGenerator.Common.TypeLibrary" Alias="TypeLibrary" />
		<Using Include="Purview.EventSourcing.SourceGenerator.Aggregate" />
		<Using Include="Purview.EventSourcing.SourceGenerator.Aggregate.Models" />
		<Using Include="Purview.EventSourcing.SourceGenerator.ValueObject" />
		<Using Include="Purview.EventSourcing.SourceGenerator.ValueObject.Models" />
	</ItemGroup>
</Project>
