<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<IsTestProject>false</IsTestProject>
		<DisableAutoInternalsVisibleTo>true</DisableAutoInternalsVisibleTo>
		<IsPackable>false</IsPackable>
		<NoWarn>$(NoWarn);TUnit0034</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SharedTestingFramework\SharedTestingFramework.csproj" />
		<ProjectReference Include="..\..\src\SqlServer\SqlServer.csproj" />
		<ProjectReference Include="..\..\src\Samples\Samples.csproj" />
	</ItemGroup>
</Project>
