// <auto-generated />

#nullable enable

namespace Purview.EventSourcing.Aggregates;

/// <summary>
/// Sets default source-generation options for all <see cref="AggregateAttribute"/> aggregates in an assembly.
/// Aggregate-level options override these defaults.
/// </summary>
//{{CodeGen}}
[global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false, Inherited = false)]
sealed class AggregateDefaultsAttribute : global::System.Attribute
{
	/// <summary>
	/// Appends a suffix to generated event type names when no explicit <see cref="EventAttribute.EventName"/> is provided.
	/// Defaults to <c>Event</c>.
	/// </summary>
	public string? EventSuffix { get; set; } = "Event";

	/// <summary>
	///  Specifies the default base class for all aggregates in the assembly.
	/// </summary>
	public global::System.Type? BaseType { get; }
}
