<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsTestProject>false</IsTestProject>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\EventSourcing\EventSourcing.csproj" />
		<ProjectReference Include="..\..\src\SourceGenerator\SourceGenerator.csproj" />
		<!--<ProjectReference
			Include="..\..\src\SourceGenerator\SourceGenerator.csproj"
			PrivateAssets="all"
			OutputItemType="Analyzer"
			ReferenceOutputAssembly="true"
		/>-->
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
		<PackageReference Include="Purview.SourceGeneratorFramework" />
	</ItemGroup>
</Project>
