<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Label="NuGet Package Values">
		<IsPackable>true</IsPackable>
		<Title>Purview In-Memory Non-Queryable and Queryable Snapshot Store</Title>
		<Description>In-memory non-queryable and queryable snapshot storage provider for Purview EventSourcing.</Description>
		<PackageId>Purview.EventSourcing.InMemory</PackageId>
		<PackageTags>$(PackageTags);purview;dotnet;testing;event-sourcing;event-store;queryable-store;snapshot;in-memory;</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\EventSourcing\EventSourcing.csproj" />
		<ProjectReference Include="..\ImplementationShared\ImplementationShared.csproj" />
	</ItemGroup>
</Project>
