namespace Purview.EventSourcing.SourceGenerator.Aggregate;

static partial class AggregateSourceEmitter
{
	public static void GenerateAggregateSource(AggregateEmitContext outputContext)
	{
		outputContext.Debug(
			$"Generating source for aggregate '{outputContext.Aggregate.AggregateClass.Identity.Name}' with {outputContext.Aggregate.Methods.Count} event methods and {outputContext.Aggregate.InvalidMethods.Count} invalid methods."
		);

		var writer = outputContext.Writer;
		writer.WriteAutoGeneratedHeader();

		// Generate event classes in nested event namespaces when commands exist.
		if (outputContext.Aggregate.IsValid && outputContext.Aggregate.Methods.Count > 0)
		{
			foreach (
				var namespaceMethods in outputContext.Aggregate.Methods.GroupBy(
					static method => method.EventType.Identity.Namespace,
					StringComparer.Ordinal
				)
			)
			{
				using (writer.WriteBlockNamespaceScope(namespaceMethods.Key))
				{
					foreach (var method in namespaceMethods)
						GenerateEventClass(outputContext, method);
				}
			}
		}

		// Generate the partial aggregate class in a block-scoped namespace.
		using var nsBlock = writer.WriteBlockNamespaceScope(outputContext.Aggregate.AggregateClass);

		List<IDisposable> containingScopes = [with(outputContext.Aggregate.ContainingTypes.Count)];
		foreach (var containingType in outputContext.Aggregate.ContainingTypes)
		{
			containingScopes.Add(
				writer.WriteClassScope(
					new(containingType.Name)
					{
						IsStatic = containingType.IsStatic,
						IsPartial = true,
						GenericTypes = [.. containingType.TypeParameters.Select(static tp => tp.Name)],
					}
				)
			);
		}

		var classAttributes = outputContext.Aggregate.IsValid
			? ImmutableArray.Create(
				new AttributeDeclarationOptions(TypeLibrary.System.TextJson.JsonConverterAttribute)
				{
					Arguments = [new($"typeof({outputContext.Aggregate.AggregateClass.Identity.Name}JsonConverter)")],
				}
			)
			: [];

		writer.WriteClass(
			new(
				outputContext.Aggregate.AggregateClass.Identity,
				outputContext.Aggregate.Accessibility.ToTypeDeclarationAccessibility()
			)
			{
				IsPartial = true,
				IsSealed = false,
				BaseType =
					outputContext.Aggregate.IsValid && outputContext.Aggregate.ShouldDeclareAggregateBase
						? TypeLibrary.Aggregates.AggregateBase
						: null,
				Attributes = classAttributes,
				GenericTypes = outputContext.Aggregate.TypeParameters,
			},
			bodyWriter =>
			{
				var localOutputContext = outputContext.WithWriter(bodyWriter);

				if (outputContext.Aggregate.IsValid)
				{
					GenerateJsonSerializationSupport(localOutputContext);

					// Generate RegisterEvents override
					GenerateRegisterEvents(localOutputContext);

					// Generate Apply methods
					foreach (var method in outputContext.Aggregate.Methods)
						GenerateApplyMethod(localOutputContext, method);

					// Generate command method implementations
					foreach (var method in outputContext.Aggregate.Methods)
					{
						if (method.IsCollectionEvent)
							CollectionCommandMethodEmitter.Generate(localOutputContext, method);
						else
							CommandMethodEmitter.Generate(localOutputContext, method);
					}

					GenerateCollectionNormalizationValidationHookDeclarations(localOutputContext);
					GeneratePropertyHookDeclarations(localOutputContext);

					foreach (var method in outputContext.Aggregate.InvalidMethods)
						GenerateInvalidCommandMethodStub(localOutputContext, method);

					GenerateJsonConverter(localOutputContext);
					GenerateJsonModel(localOutputContext);
				}
				else
				{
					if (
						outputContext.Aggregate.InheritsAggregateBase
						&& !outputContext.Aggregate.HasManualRegisterEvents
					)
					{
						writer.WriteMethod(
							new("RegisterEvents", TypeDeclarationAccessibility.Protected) { IsOverride = true },
							_ => { }
						);
					}

					foreach (var method in outputContext.Aggregate.Methods)
						GenerateInvalidCommandMethodStub(localOutputContext, method);

					foreach (var method in outputContext.Aggregate.InvalidMethods)
						GenerateInvalidCommandMethodStub(localOutputContext, method);
				}
			}
		);

		foreach (var scope in Enumerable.Reverse(containingScopes))
			scope.Dispose();
	}

	static void GenerateRegisterEvents(AggregateEmitContext outputContext)
	{
		outputContext.Writer.WriteMethod(
			new("RegisterEvents", TypeDeclarationAccessibility.Protected) { IsOverride = true },
			bodyWriter =>
			{
				foreach (var method in outputContext.Aggregate.Methods)
				{
					bodyWriter.Write($"Register<").Write(method.EventType).WriteLine(">(Apply);");
				}
			}
		);
	}

	static void GenerateJsonSerializationSupport(AggregateEmitContext outputContext)
	{
		TypeIdentity jsonModel = new($"{outputContext.Aggregate.AggregateClass.Identity.Name}JsonModel", null);

		outputContext.Writer.WriteMethod(
			new(
				"CreateFromJsonModel",
				new TypeReference(new TypeIdentity(outputContext.Aggregate.AggregateClass.Identity.Name, null)),
				TypeDeclarationAccessibility.Internal
			)
			{
				IsStatic = true,
				Parameters = [new("jsonModel", jsonModel)],
			},
			writeBody =>
			{
				writeBody.Write("var aggregate = new ").Write(outputContext.Aggregate.AggregateClass);
				using (writeBody.OpenBlockScope())
				{
					writeBody.WriteLine(
						$"Details = jsonModel.Details ?? new {TypeLibrary.Aggregates.AggregateDetails}(),"
					);

					foreach (var property in outputContext.Aggregate.Properties)
						writeBody.WriteLine($"{property.PropertyName} = jsonModel.{property.PropertyName},");
				}
				writeBody.Write(";").NewLine();

				writeBody.WriteReturn("aggregate");
			}
		);

		outputContext.Writer.WriteMethod(
			new("ToJsonModel", jsonModel, TypeDeclarationAccessibility.Internal),
			writeBody =>
				writeBody
					.OpenBlock(
						"return new()",
						returnBlock =>
						{
							returnBlock.WriteLine("Details = Details,");

							foreach (var property in outputContext.Aggregate.Properties)
							{
								returnBlock
									.Write(property.PropertyName)
									.Write(" = ")
									.Write(property.PropertyName)
									.WriteLine(",");
							}
						}
					)
					.WriteLine(";")
		);
	}

	static void GenerateApplyMethod(AggregateEmitContext outputContext, AggregateEventMethodInfo method)
	{
		if (method.UserApplyMethodKind == UserApplyMethodKind.NonPartial)
		{
			// User supplied a complete, non-partial Apply(...) implementation.
			return;
		}

		if (method.UserApplyMethodKind == UserApplyMethodKind.PartialImplementation || method.ManualApply)
		{
			// If the user is providing a partial implementation or is manually applying the event, we generate a partial method declaration for Apply(...) with the appropriate accessibility.
			outputContext.Writer.WritePartialMethod(
				new("Apply", accessibility: method.ManualApply ? method.UserApplyMethodAccessibility : null)
				{
					IsPartial = true,
					Parameters = [new("@event", method.EventType)],
				}
			);

			return;
		}

		if (method.IsCollectionEvent)
		{
			GenerateCollectionApplyMethod(outputContext, method);
			return;
		}

		const string eventParameterName = "@event";
		var mappedParameters = method.AllParameters.Where(static parameter => parameter.HasAggregateProperty).ToList();

		outputContext.Writer.WriteMethod(
			new("Apply", TypeDeclarationAccessibility.Private)
			{
				Parameters = [new(eventParameterName, method.EventType)],
			},
			applyBody =>
			{
				var applyOutputContext = outputContext.WithWriter(applyBody);
				foreach (var prop in mappedParameters)
					applyBody.WriteAssignment(
						"var",
						$"__previous{prop.AggregatePropertyName}",
						prop.AggregatePropertyName
					);

				if (mappedParameters.Count > 0)
					applyBody.NewLine();

				foreach (var prop in mappedParameters)
					applyBody.WriteAssignment(prop.AggregatePropertyName, $"{eventParameterName}.{prop.PropertyName}");

				if (mappedParameters.Count > 0)
					applyBody.NewLine();

				foreach (var prop in mappedParameters)
					applyBody.WriteMethodCall(
						$"On{prop.AggregatePropertyName}Changed",
						[$"__previous{prop.AggregatePropertyName}", prop.AggregatePropertyName]
					);

				applyBody.WriteMethodCall($"OnApplied{GetHookName(method.EventType)}", eventParameterName);
			}
		);
	}

	internal static string GetHookName(TypeReference eventType)
	{
		var eventName = eventType.Identity.Name;
		if (!eventName.EndsWith("Event", StringComparison.Ordinal))
			eventName += "Event";

		return eventName;
	}

	static void GenerateCollectionApplyMethod(AggregateEmitContext outputContext, AggregateEventMethodInfo method)
	{
		var collectionEvent = method.CollectionEvent!;
		var parameter = method.AllParameters[0];
		const string eventParameterName = "@event";
		var hookSuffix = GetHookName(method.EventType);
		var operationMethod = collectionEvent.Operation == CollectionMutationOperation.Add ? "Add" : "Remove";

		outputContext.Writer.WriteMethod(
			new("Apply", TypeDeclarationAccessibility.Private)
			{
				Parameters = [new(eventParameterName, method.EventType)],
			},
			writeBody =>
			{
				writeBody.WriteBlock(
					$"if ({collectionEvent.PropertyName} is null)",
					block =>
						block.WriteThrow(
							$"new global::System.InvalidOperationException(\"Collection property '{collectionEvent.PropertyName}' cannot be null when applying {method.EventType}.\");"
						)
				);

				if (collectionEvent.ParameterShape == CollectionParameterShape.Single)
				{
					writeBody.WriteLine(
						$"(({TypeLibrary.System.Collections.Generic.ICollection.MakeGeneric(collectionEvent.ElementType)})"
							+ $"{collectionEvent.PropertyName}).{operationMethod}({eventParameterName}.{parameter.PropertyName});"
					);
				}
				else
				{
					writeBody.WriteBlock(
						$"foreach (var __item in {eventParameterName}.{parameter.PropertyName})",
						block =>
							block.WriteLine(
								$"(({TypeLibrary.System.Collections.Generic.ICollection.MakeGeneric(collectionEvent.ElementType)})"
									+ $"{collectionEvent.PropertyName}).{operationMethod}(__item);"
							)
					);
				}

				writeBody.WriteMethodCall($"OnApplied{hookSuffix}", eventParameterName);
			}
		);
	}

	static void GeneratePropertyHookDeclarations(AggregateEmitContext outputContext)
	{
		var writer = outputContext.Writer;
		var aggregateProperties = outputContext
			.Aggregate.Methods.SelectMany(static method => method.AllParameters)
			.Where(static parameter => parameter.HasAggregateProperty)
			.GroupBy(static parameter => parameter.AggregatePropertyName, StringComparer.Ordinal)
			.Select(static group => group.First())
			.ToList();

		var suppression = CreateCA1822Suppression();
		foreach (var prop in aggregateProperties)
		{
			var changingValueType = prop.RequiresLocalCopy ? prop.PropertyType : prop.ParameterType;
			writer.WritePartialMethod(
				new($"On{prop.AggregatePropertyName}Changing")
				{
					Attributes = [suppression],
					Parameters = [new(prop.ParameterName, changingValueType, ParameterModifier.Ref)],
				}
			);

			writer.WritePartialMethod(
				new($"On{prop.AggregatePropertyName}Changed")
				{
					Attributes = [suppression],
					Parameters = [new("previous", prop.PropertyType), new("current", prop.PropertyType)],
				}
			);
		}
	}

	static void GenerateCollectionNormalizationValidationHookDeclarations(AggregateEmitContext outputContext)
	{
		var writer = outputContext.Writer;
		var declaredKeys = new HashSet<string>(StringComparer.Ordinal);
		foreach (var method in outputContext.Aggregate.Methods.Where(static method => method.IsCollectionEvent))
		{
			var collectionEvent = method.CollectionEvent!;
			var parameter = method.AllParameters[0];
			var declarationType =
				collectionEvent.ParameterShape == CollectionParameterShape.Single
					? collectionEvent.ElementType
					: TypeLibrary
						.System.Collections.Generic.IEnumerable.MakeGeneric(collectionEvent.ElementType)
						.AsTypeReference();
			var key = $"{collectionEvent.NormalizeValidateHookSuffix}|{declarationType}";
			if (!declaredKeys.Add(key))
				continue;

			var suppression = CreateCA1822Suppression();
			ParameterDeclarationOptions param = new(parameter.ParameterName, declarationType);
			writer.WritePartialMethod(
				new($"OnNormalizing{collectionEvent.NormalizeValidateHookSuffix}")
				{
					Attributes = [suppression],
					Parameters = [param with { Modifier = ParameterModifier.Ref }],
				}
			);

			writer.WritePartialMethod(
				new($"OnValidating{collectionEvent.NormalizeValidateHookSuffix}")
				{
					Attributes = [suppression],
					Parameters = [param with { Modifier = ParameterModifier.Ref }],
				}
			);
		}
	}

	public static AttributeDeclarationOptions CreateCA1822Suppression() =>
		new(TypeLibrary.System.DiagnosticsCodeAnalysis.SuppressMessageAttribute)
		{
			Arguments =
			[
				new("\"Performance\""),
				new("\"CA1822:Mark members as static\""),
				new(
					"\"Generated partial hook declaration must match instance signature and cannot be static.\"",
					"Justification",
					true
				),
			],
		};

	internal static string GetLocalValueName(EventPropertyInfo parameter) => $"__{parameter.ParameterName}Value";

	internal static ImmutableArray<MethodCallArgumentOptions> BuildOnCreatingCallArgumentList(
		ImmutableArray<EventPropertyInfo> parameters
	) =>
		[
			.. parameters.Select(static parameter => new MethodCallArgumentOptions(
				GetWorkingValueName(parameter),
				ParameterModifier.Ref
			)),
		];

	internal static ImmutableArray<ParameterDeclarationOptions> BuildOnCreatingDeclarationParameterList(
		ImmutableArray<EventPropertyInfo> parameters
	) =>
		[
			.. parameters.Select(static parameter => new ParameterDeclarationOptions(
				parameter.ParameterName,
				parameter.RequiresLocalCopy ? parameter.PropertyType : parameter.ParameterType,
				ParameterModifier.Ref
			)),
		];

	internal static void EmitEventCreation(
		AggregateEmitContext outputContext,
		AggregateEventMethodInfo method,
		bool declareVariable
	)
	{
		var writer = outputContext.Writer;
		writer.Write(declareVariable ? "var @event = new " : "@event = new ").Write(method.EventType);
		using (writer.OpenBlockScope())
		{
			foreach (var prop in method.EventParameters)
			{
				var valueExpression = GetWorkingValueName(prop);
				if (prop.IsNotNull || prop.IsRequired)
					valueExpression += "!";

				writer.WriteLine($"{prop.PropertyName} = {valueExpression},");
			}
		}
		writer.Write(";").NewLine();
	}

	internal static string BuildPropertyValueExpression(
		AggregateEmitContext outputContext,
		AggregateEventMethodInfo method,
		EventPropertyInfo parameter
	)
	{
		return parameter.ParameterConversionKind switch
		{
			EventParameterConversionKind.None => parameter.ParameterName,
			EventParameterConversionKind.Implicit => $"({parameter.PropertyType}){parameter.ParameterName}",
			EventParameterConversionKind.Create => $"{parameter.PropertyType}.Create({parameter.ParameterName})",
			EventParameterConversionKind.ContextualCreate =>
				$"{parameter.PropertyType}.Create({parameter.ParameterName}, new global::Purview.EventSourcing.ValueObjects.ValueObjectContext<{outputContext.Aggregate.AggregateClass}>(this, MemberName: nameof({parameter.AggregatePropertyName}), EventName: nameof({method.EventType})))",
			_ => parameter.ParameterName,
		};
	}

	internal static string BuildUnchangedCondition(List<EventPropertyInfo> parameters)
	{
		return string.Join(" && ", parameters.Select(BuildUnchangedComparison));
	}

	static string BuildUnchangedComparison(EventPropertyInfo parameter)
	{
		var comparisonValue = GetWorkingValueName(parameter);

		return parameter.UseStringOrdinalComparison
			? $"global::System.String.Equals({parameter.AggregatePropertyName}, {comparisonValue}, global::System.StringComparison.Ordinal)"
			: $"global::System.Collections.Generic.EqualityComparer<{parameter.EqualityComparerTypeName}>.Default.Equals({parameter.AggregatePropertyName}, {comparisonValue})";
	}

	internal static string GetWorkingValueName(EventPropertyInfo parameter) =>
		parameter.RequiresLocalCopy ? GetLocalValueName(parameter) : parameter.ParameterName;

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases")]
	internal static CodeWriter EmitNoChangeReturn(AggregateEmitContext outputContext, EventMethodReturnKind returnKind)
	{
		var writer = outputContext.Writer;
		return returnKind switch
		{
			EventMethodReturnKind.Aggregate => writer.WriteReturn("this"),
			EventMethodReturnKind.Bool => writer.WriteReturn("false"),
			_ => writer.WriteReturn(),
		};
	}

	internal static void EmitSuccessReturn(AggregateEmitContext outputContext, EventMethodReturnKind returnKind)
	{
		var writer = outputContext.Writer;
		if (returnKind == EventMethodReturnKind.Aggregate)
			writer.WriteReturn("this");
		else if (returnKind == EventMethodReturnKind.Bool)
			writer.WriteReturn("true");
		else
			writer.WriteReturn();
	}

	static void GenerateInvalidCommandMethodStub(
		AggregateEmitContext outputContext,
		InvalidAggregateEventMethodInfo method
	)
	{
		var diagnosticIds = !method.DiagnosticIds.IsEmpty
			? string.Join(", ", method.DiagnosticIds)
			: "unknown diagnostic IDs";
		var message = EscapeStringLiteral(
			$"The generated aggregate event method '{method.Signature}' is unavailable because [Event] validation failed. Review the suppressed generator diagnostics for this method ({diagnosticIds})."
		);

		using (outputContext.Writer.OpenBlockScope(method.Signature))
		{
			outputContext.Writer.WriteThrow($"new global::System.InvalidOperationException(\"{message}\")");
		}
		outputContext.Writer.NewLine();
	}

	static void GenerateInvalidCommandMethodStub(AggregateEmitContext outputContext, AggregateEventMethodInfo method)
	{
		var signature = string.IsNullOrWhiteSpace(method.Signature)
			? BuildSignatureFromMethodInfo(method)
			: method.Signature;

		using (outputContext.Writer.OpenBlockScope(signature))
		{
			outputContext.Writer.WriteThrow(
				"new global::System.InvalidOperationException(\"The generated aggregate event method is unavailable because aggregate validation failed.\");"
			);
		}
		outputContext.Writer.NewLine();
	}

	static string BuildSignatureFromMethodInfo(AggregateEventMethodInfo method)
	{
		var parameterList = BuildParameterList(method.AllParameters);
		var accessModifier = GetAccessModifierString(method.MethodAccessibility);
		return $"{accessModifier} partial {method.ReturnType} {method.MethodName}({parameterList})";
	}

	static string EscapeStringLiteral(string value) =>
		value
			.Replace("\\", "\\\\")
			.Replace("\"", "\\\"")
			.Replace("\r", "\\r")
			.Replace("\n", "\\n")
			.Replace("\t", "\\t");

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases")]
	internal static TypeDeclarationAccessibility GetAccessModifier(Accessibility accessibility)
	{
		return accessibility switch
		{
			Accessibility.Public => TypeDeclarationAccessibility.Public,
			Accessibility.Private => TypeDeclarationAccessibility.Private,
			Accessibility.Internal => TypeDeclarationAccessibility.Internal,
			Accessibility.Protected => TypeDeclarationAccessibility.Protected,
			Accessibility.ProtectedOrInternal => TypeDeclarationAccessibility.ProtectedInternal,
			Accessibility.ProtectedAndInternal => TypeDeclarationAccessibility.PrivateProtected,
			_ => TypeDeclarationAccessibility.Internal,
		};
	}

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases")]
	internal static string GetAccessModifierString(Accessibility accessibility) =>
		accessibility switch
		{
			Accessibility.Public => "public",
			Accessibility.Private => "private",
			Accessibility.Internal => "internal",
			Accessibility.Protected => "protected",
			Accessibility.ProtectedOrInternal => "protected internal",
			Accessibility.ProtectedAndInternal => "private protected",
			_ => "internal",
		};

	internal static string BuildParameterList(ImmutableArray<EventPropertyInfo> parameters)
	{
		if (parameters.Length == 0)
			return string.Empty;

		var parts = new string[parameters.Length];
		for (var i = 0; i < parameters.Length; i++)
		{
			var parameter = parameters[i];
			var prefix = parameter.IsParams ? "params " : string.Empty;
			parts[i] = $"{prefix}{parameter.ParameterType} {parameter.ParameterName}";
		}

		return string.Join(", ", parts);
	}

	static void GenerateJsonConverter(AggregateEmitContext outputContext)
	{
		var writer = outputContext.Writer;
		TypeIdentity jsonModel = new($"{outputContext.Aggregate.AggregateClass.Identity.Name}JsonModel", null);

		writer.WriteClass(
			new($"{outputContext.Aggregate.AggregateClass.Identity.Name}JsonConverter")
			{
				IsPartial = false,
				IsSealed = true,
				BaseType = TypeLibrary.System.TextJson.JsonConverter.MakeGeneric(
					outputContext.Aggregate.AggregateClass
				),
			},
			bodyWriter =>
			{
				bodyWriter.WriteMethod(
					new("Read", outputContext.Aggregate.AggregateClass.Nullable(), TypeDeclarationAccessibility.Public)
					{
						IsOverride = true,
						Parameters =
						[
							new("reader", TypeLibrary.System.TextJson.Utf8JsonReader, ParameterModifier.Ref),
							new("typeToConvert", PurviewTypeLibrary.System.Type),
							new("options", TypeLibrary.System.TextJson.JsonSerializerOptions),
						],
					},
					methodWriter =>
					{
						methodWriter.WriteAssignment(
							"var",
							"jsonModel",
							writeValue =>
								writeValue.WriteMethodCall(
									TypeLibrary.System.TextJson.JsonSerializer.StaticMember("Deserialize"),
									[new MethodCallArgumentOptions("reader", ParameterModifier.Ref), "options"],
									genericArguments: [jsonModel]
								)
						);

						methodWriter.WriteIfBlock(
							"jsonModel is null",
							ifBlock =>
								ifBlock.WriteThrow(
									$"new {TypeLibrary.System.TextJson.JsonException}(\"Unable to deserialize {outputContext.Aggregate.AggregateClass}.\")"
								)
						);

						methodWriter.WriteReturn(writerExpression =>
							writerExpression.WriteMethodCall(
								outputContext.Aggregate.AggregateClass.Identity.StaticMember("CreateFromJsonModel"),
								["jsonModel"]
							)
						);
					}
				);

				bodyWriter.WriteMethod(
					new("Write", TypeDeclarationAccessibility.Public)
					{
						IsOverride = true,
						Parameters =
						[
							new("writer", TypeLibrary.System.TextJson.Utf8JsonWriter),
							new("value", outputContext.Aggregate.AggregateClass),
							new("options", TypeLibrary.System.TextJson.JsonSerializerOptions),
						],
					},
					bodyWriter =>
						bodyWriter.WriteMethodCall(
							TypeLibrary.System.TextJson.JsonSerializer.StaticMember("Serialize"),
							["writer", "value.ToJsonModel()", "options"]
						)
				);
			}
		);
	}

	static void GenerateJsonModel(AggregateEmitContext outputContext)
	{
		var writer = outputContext.Writer;

		writer.WriteClass(
			new(
				$"{outputContext.Aggregate.AggregateClass.Identity.Name}JsonModel",
				TypeDeclarationAccessibility.Internal
			)
			{
				IsPartial = false,
				IsSealed = true,
			},
			bodyWriter =>
			{
				bodyWriter.WriteProperty(
					new(
						"Details",
						TypeLibrary.Aggregates.AggregateDetails.MakeNullable(),
						TypeDeclarationAccessibility.Public
					)
					{
						HasSetter = true,
						Initializer = "new()",
					}
				);
				foreach (var property in outputContext.Aggregate.Properties)
				{
					bodyWriter.WriteProperty(
						new(property.PropertyName, property.PropertyType, TypeDeclarationAccessibility.Public)
						{
							HasSetter = true,
							Initializer = "default!",
						}
					);
				}
			}
		);
	}
}
