using System.Text;
using Microsoft.CodeAnalysis;

namespace Purview.EventSourcing.SourceGenerator.Aggregate;

static class AggregateSourceEmitter
{
	public static void GenerateAggregateSource(
		CodeWriter writer,
		AggregateInfo info,
		GenerationLogger? logger
	)
	{
		logger?.Debug(
			$"Generating source for aggregate '{info.AggregateClass.TypeName}' with {info.Methods.Count} event methods and {info.InvalidMethods.Count} invalid methods."
		);

		writer.WriteAutoGeneratedHeader();

		// Generate event classes in a nested Events namespace
		if (info.Methods.Count > 0)
		{
			foreach (
				var namespaceMethods in info.Methods.GroupBy(
					static method => method.EventNamespace,
					StringComparer.Ordinal
				)
			)
			{
				writer.WriteLine($"namespace {namespaceMethods.Key}");
				writer.WriteLine("{");

				foreach (var method in namespaceMethods)
				{
					GenerateEventClass(writer, method, logger);
				}

				writer.WriteLine("}");
				writer.WriteLine();
			}
		}

		// Generate the partial aggregate class in a block-scoped namespace
		// (required because event classes use a different namespace in the same file)
		var accessModifier = GetAccessModifier(info.Accessibility);

		if (info.AggregateClass.Namespace is not null)
		{
			writer.WriteLine($"namespace {info.AggregateClass.Namespace}");
			writer.WriteLine("{");
		}

		var indent = info.AggregateClass.Namespace is not null ? "\t" : "";

		writer.WriteLine(
			$"{indent}[global::System.Text.Json.Serialization.JsonConverter(typeof({info.AggregateClass.TypeName}JsonConverter))]"
		);
		var aggregateBaseClause = info.ShouldDeclareAggregateBase
			? " : global::Purview.EventSourcing.Aggregates.AggregateBase"
			: string.Empty;
		writer.WriteLine(
			$"{indent}{accessModifier} partial class {info.AggregateClass.TypeName}{aggregateBaseClause}"
		);
		writer.WriteLine($"{indent}{{");

		GenerateJsonSerializationSupport(writer, info, indent);

		// Generate RegisterEvents override
		GenerateRegisterEvents(writer, info, indent);

		// Generate Apply methods
		foreach (var method in info.Methods)
		{
			GenerateApplyMethod(writer, info, method, indent);
		}

		// Generate command method implementations
		foreach (var method in info.Methods)
		{
			if (method.IsCollectionEvent)
				CollectionCommandMethodEmitter.Generate(writer, info, method, indent);
			else
				CommandMethodEmitter.Generate(writer, info, method, indent);
		}

		GenerateCollectionNormalizationValidationHookDeclarations(writer, info, indent);
		GeneratePropertyHookDeclarations(writer, info, indent);

		foreach (var method in info.InvalidMethods)
		{
			GenerateInvalidCommandMethodStub(writer, method, indent);
		}

		writer.WriteLine($"{indent}}}");

		GenerateJsonConverter(writer, info, indent);
		GenerateJsonModel(writer, info, indent);

		if (info.AggregateClass.Namespace is not null)
		{
			writer.WriteLine("}");
		}

		return;
	}

	static class CommandMethodEmitter
	{
		public static void Generate(
			CodeWriter writer,
			AggregateInfo info,
			AggregateEventMethodInfo method,
			string indent
		)
		{
			var paramList = BuildParameterList(method);
			var computedParameters = method
				.Parameters.Where(static parameter => parameter.IsComputed)
				.ToList();
			var nonComputedParameters = method
				.Parameters.Where(static parameter => !parameter.IsComputed)
				.ToList();
			var storedParameters = method
				.Parameters.Where(static parameter => parameter.IncludeInEvent)
				.ToList();
			var hookSuffix = GetHookName(method.EventName);
			var methodAccessModifier = GetAccessModifier(method.MethodAccessibility);

			writer.WriteLine(
				$"{indent}\t{methodAccessModifier} partial {method.ReturnTypeName} {method.MethodName}({paramList})"
			);
			writer.WriteLine($"{indent}\t{{");

			if (method.Parameters.Count > 0)
				EmitParameterPreparationBlock(writer, info, method, indent);

			if (computedParameters.Count > 0)
				EmitOnComputingBefore(writer, method, computedParameters, hookSuffix, indent);

			EmitEventCreationAndShouldApply(
				writer,
				method,
				storedParameters,
				hookSuffix,
				indent,
				declareVariable: true
			);
			writer.WriteLine();
			EmitRaisingHook(
				writer,
				method,
				computedParameters,
				nonComputedParameters,
				hookSuffix,
				indent
			);

			if (computedParameters.Count > 0)
			{
				writer.WriteLine();
				EmitOnComputingAfter(writer, method, computedParameters, hookSuffix, indent);
			}

			EmitEventCreationAndShouldApply(
				writer,
				method,
				storedParameters,
				hookSuffix,
				indent,
				declareVariable: false
			);

			if (method.Parameters.Count > 0)
			{
				var mappedParameters = method
					.Parameters.Where(static parameter => parameter.HasAggregateProperty)
					.ToList();

				if (mappedParameters.Count > 0)
				{
					writer.WriteLine();
					EmitUnchangedCheck(writer, method, mappedParameters, indent);
				}
			}

			EmitFinalization(writer, method, hookSuffix, indent);

			writer.WriteLine($"{indent}\t}}");
			writer.WriteLine();

			EmitHookDeclarations(
				writer,
				method,
				computedParameters,
				nonComputedParameters,
				hookSuffix,
				indent
			);
		}

		static string BuildParameterList(AggregateEventMethodInfo method)
		{
			var paramList = new StringBuilder();
			for (var i = 0; i < method.Parameters.Count; i++)
			{
				if (i > 0)
					paramList.Append(", ");
				var paramsPrefix = method.Parameters[i].IsParams ? "params " : string.Empty;
				paramList.Append(
					$"{paramsPrefix}{method.Parameters[i].ParameterTypeName} {method.Parameters[i].ParameterName}"
				);
			}

			return paramList.ToString();
		}

		static void EmitParameterPreparationBlock(
			CodeWriter writer,
			AggregateInfo info,
			AggregateEventMethodInfo method,
			string indent
		)
		{
			var mappedParameters = method
				.Parameters.Where(static parameter => parameter.HasAggregateProperty)
				.ToList();

			foreach (var prop in method.Parameters)
			{
				if (prop.IsComputed)
				{
					writer.WriteLine(
						$"{indent}\t\tvar {GetLocalValueName(prop)} = {prop.ParameterName};"
					);
					continue;
				}

				if (prop.ParameterConversionKind is not EventParameterConversionKind.None)
				{
					writer.WriteLine(
						$"{indent}\t\tvar {GetLocalValueName(prop)} = {BuildPropertyValueExpression(info, method, prop)};"
					);
					continue;
				}
			}

			if (
				method.Parameters.Any(static p =>
					p.IsComputed
					|| p.ParameterConversionKind is not EventParameterConversionKind.None
				)
			)
				writer.WriteLine();

			var computedParameters = method
				.Parameters.Where(static parameter => parameter.IsComputed)
				.ToList();

			foreach (var prop in computedParameters)
			{
				writer.WriteLine(
					$"{indent}\t\tif (!global::System.Collections.Generic.EqualityComparer<{prop.PropertyTypeName}>.Default.Equals({prop.ParameterName}, default({prop.PropertyTypeName})))"
				);
				writer.WriteLine($"{indent}\t\t{{");
				writer.WriteLine(
					$"{indent}\t\t\tthrow new global::System.ArgumentException(\"Computed parameter '{prop.ParameterName}' cannot be set by callers.\", nameof({prop.ParameterName}));"
				);
				writer.WriteLine($"{indent}\t\t}}");
			}

			if (computedParameters.Count > 0)
				writer.WriteLine();

			EmitValidationGuards(writer, method, indent);

			foreach (var prop in mappedParameters)
			{
				writer.WriteLine(
					$"{indent}\t\tOn{prop.AggregatePropertyName}Changing(ref {GetWorkingValueName(prop)});"
				);
			}

			if (mappedParameters.Count > 0)
				writer.WriteLine();
		}

		static void EmitValidationGuards(
			CodeWriter writer,
			AggregateEventMethodInfo method,
			string indent
		)
		{
			var emitted = false;
			foreach (var prop in method.Parameters)
			{
				if (prop.IsComputed)
					continue;

				if (prop.ParameterConversionKind is not EventParameterConversionKind.None)
					continue;

				if (!prop.RequiresLocalCopy)
					continue;

				if (prop.IsRequired && prop.IsString)
				{
					writer.WriteLine(
						$"{indent}\t\tif (global::System.String.IsNullOrWhiteSpace({prop.ParameterName}))"
					);
					writer.WriteLine($"{indent}\t\t{{");
					writer.WriteLine(
						$"{indent}\t\t\tthrow new global::System.ArgumentException(\"Parameter '{prop.ParameterName}' cannot be null or empty.\", nameof({prop.ParameterName}));"
					);
					writer.WriteLine($"{indent}\t\t}}");
				}
				else if (prop.IsRequired || prop.IsNotNull)
				{
					writer.WriteLine($"{indent}\t\tif ({prop.ParameterName} is null)");
					writer.WriteLine($"{indent}\t\t{{");
					writer.WriteLine(
						$"{indent}\t\t\tthrow new global::System.ArgumentNullException(nameof({prop.ParameterName}));"
					);
					writer.WriteLine($"{indent}\t\t}}");
				}

				writer.WriteLine(
					$"{indent}\t\tvar {GetLocalValueName(prop)} = {prop.ParameterName}!;"
				);

				emitted = true;
			}

			if (emitted)
				writer.WriteLine();
		}

		static void EmitOnComputingBefore(
			CodeWriter writer,
			AggregateEventMethodInfo method,
			List<EventPropertyInfo> computedParameters,
			string hookSuffix,
			string indent
		)
		{
			writer.WriteLine(
				$"{indent}\t\tOnComputing{hookSuffix}({BuildOnCreatingCallArgumentList(computedParameters)});"
			);
			writer.WriteLine(
				$"{indent}\t\tOnComputing{hookSuffix}({BuildOnCreatingCallArgumentList(method.Parameters)});"
			);
			writer.WriteLine();
		}

		static void EmitEventCreationAndShouldApply(
			CodeWriter writer,
			AggregateEventMethodInfo method,
			List<EventPropertyInfo> storedParameters,
			string hookSuffix,
			string indent,
			bool declareVariable
		)
		{
			EmitEventCreation(writer, method, storedParameters, indent, declareVariable);
			writer.WriteLine($"{indent}\t\tif (!ShouldApply{hookSuffix}(@event))");
			writer.WriteLine($"{indent}\t\t{{");
			EmitNoChangeReturn(writer, method.ReturnKind, indent, 3);
			writer.WriteLine($"{indent}\t\t}}");
		}

		static void EmitRaisingHook(
			CodeWriter writer,
			AggregateEventMethodInfo method,
			List<EventPropertyInfo> computedParameters,
			List<EventPropertyInfo> nonComputedParameters,
			string hookSuffix,
			string indent
		)
		{
			if (method.Parameters.Count == 0)
				writer.WriteLine($"{indent}\t\tOnRaising{hookSuffix}();");
			else if (computedParameters.Count > 0)
			{
				if (nonComputedParameters.Count == 0)
					writer.WriteLine($"{indent}\t\tOnRaising{hookSuffix}();");
				else
					writer.WriteLine(
						$"{indent}\t\tOnRaising{hookSuffix}({BuildOnCreatingCallArgumentList(nonComputedParameters)});"
					);
				writer.WriteLine(
					$"{indent}\t\tOnRaising{hookSuffix}({BuildOnCreatingCallArgumentList(method.Parameters)});"
				);
			}
			else
			{
				writer.WriteLine(
					$"{indent}\t\tOnRaising{hookSuffix}({BuildOnCreatingCallArgumentList(method.Parameters)});"
				);
			}
		}

		static void EmitOnComputingAfter(
			CodeWriter writer,
			AggregateEventMethodInfo method,
			List<EventPropertyInfo> computedParameters,
			string hookSuffix,
			string indent
		)
		{
			writer.WriteLine(
				$"{indent}\t\tOnComputing{hookSuffix}({BuildOnCreatingCallArgumentList(computedParameters)});"
			);
			writer.WriteLine(
				$"{indent}\t\tOnComputing{hookSuffix}({BuildOnCreatingCallArgumentList(method.Parameters)});"
			);
		}

		static void EmitUnchangedCheck(
			CodeWriter writer,
			AggregateEventMethodInfo method,
			List<EventPropertyInfo> mappedParameters,
			string indent
		)
		{
			writer.WriteLine($"{indent}\t\tif ({BuildUnchangedCondition(mappedParameters)})");
			writer.WriteLine($"{indent}\t\t{{");
			EmitNoChangeReturn(writer, method.ReturnKind, indent, 3);
			writer.WriteLine($"{indent}\t\t}}");
		}

		static void EmitFinalization(
			CodeWriter writer,
			AggregateEventMethodInfo method,
			string hookSuffix,
			string indent
		)
		{
			writer.WriteLine($"{indent}\t\tOnRaised{hookSuffix}(@event);");
			writer.WriteLine($"{indent}\t\tRecordAndApply(@event);");
			writer.WriteLine();
			EmitSuccessReturn(writer, method.ReturnKind, indent, 2);
		}

		static void EmitHookDeclarations(
			CodeWriter writer,
			AggregateEventMethodInfo method,
			List<EventPropertyInfo> computedParameters,
			List<EventPropertyInfo> nonComputedParameters,
			string hookSuffix,
			string indent
		)
		{
			if (computedParameters.Count > 0)
			{
				EmitCa1822Suppression(writer, indent);
				writer.WriteLine(
					$"{indent}\tpartial void OnComputing{hookSuffix}({BuildOnCreatingDeclarationParameterList(computedParameters)});"
				);
				EmitCa1822Suppression(writer, indent);
				writer.WriteLine(
					$"{indent}\tpartial void OnComputing{hookSuffix}({BuildOnCreatingDeclarationParameterList(method.Parameters)});"
				);
			}

			EmitCa1822Suppression(writer, indent);
			if (method.Parameters.Count == 0)
				writer.WriteLine($"{indent}\tpartial void OnRaising{hookSuffix}();");
			else if (computedParameters.Count > 0)
			{
				if (nonComputedParameters.Count == 0)
					writer.WriteLine($"{indent}\tpartial void OnRaising{hookSuffix}();");
				else
					writer.WriteLine(
						$"{indent}\tpartial void OnRaising{hookSuffix}({BuildOnCreatingDeclarationParameterList(nonComputedParameters)});"
					);
				EmitCa1822Suppression(writer, indent);
				writer.WriteLine(
					$"{indent}\tpartial void OnRaising{hookSuffix}({BuildOnCreatingDeclarationParameterList(method.Parameters)});"
				);
			}
			else
			{
				writer.WriteLine(
					$"{indent}\tpartial void OnRaising{hookSuffix}({BuildOnCreatingDeclarationParameterList(method.Parameters)});"
				);
			}

			EmitCa1822Suppression(writer, indent);
			writer.WriteLine(
				$"{indent}\tbool ShouldApply{hookSuffix}(global::{method.EventNamespace}.{method.EventName} @event)"
			);
			writer.WriteLine($"{indent}\t{{");
			writer.WriteLine($"{indent}\t\tvar shouldApply = true;");
			writer.WriteLine($"{indent}\t\tOnShouldApply{hookSuffix}(@event, ref shouldApply);");
			writer.WriteLine($"{indent}\t\treturn shouldApply;");
			writer.WriteLine($"{indent}\t}}");
			EmitCa1822Suppression(writer, indent);
			writer.WriteLine(
				$"{indent}\tpartial void OnShouldApply{hookSuffix}(global::{method.EventNamespace}.{method.EventName} @event, ref bool shouldApply);"
			);
			EmitCa1822Suppression(writer, indent);
			writer.WriteLine(
				$"{indent}\tpartial void OnRaised{hookSuffix}(global::{method.EventNamespace}.{method.EventName} @event);"
			);
			EmitCa1822Suppression(writer, indent);
			writer.WriteLine(
				$"{indent}\tpartial void OnApplied{hookSuffix}(global::{method.EventNamespace}.{method.EventName} @event);"
			);
			writer.WriteLine();
		}
	}

	static class CollectionCommandMethodEmitter
	{
		public static void Generate(
			CodeWriter writer,
			AggregateInfo _,
			AggregateEventMethodInfo method,
			string indent
		)
		{
			var collectionEvent = method.CollectionEvent!;
			var parameter = method.Parameters[0];
			var hookSuffix = GetHookName(method.EventName);
			var normalizeValidateSuffix = collectionEvent.NormalizeValidateHookSuffix;
			var methodAccessModifier = GetAccessModifier(method.MethodAccessibility);

			writer.WriteLine(
				$"{indent}\t{methodAccessModifier} partial {method.ReturnTypeName} {method.MethodName}({(parameter.IsParams ? "params " : string.Empty)}{parameter.ParameterTypeName} {parameter.ParameterName})"
			);
			writer.WriteLine($"{indent}\t{{");

			EmitCollectionGuard(writer, collectionEvent, indent);

			if (collectionEvent.ParameterShape == CollectionParameterShape.Single)
				EmitSingleItemBody(
					writer,
					method,
					collectionEvent,
					parameter,
					hookSuffix,
					normalizeValidateSuffix,
					indent
				);
			else
				EmitEnumerableBody(
					writer,
					method,
					collectionEvent,
					parameter,
					hookSuffix,
					normalizeValidateSuffix,
					indent
				);

			EmitCollectionFinalization(writer, method, hookSuffix, indent);

			writer.WriteLine($"{indent}\t}}");
			writer.WriteLine();

			EmitCollectionTrailingHookDeclarations(
				writer,
				method,
				collectionEvent,
				parameter,
				hookSuffix,
				indent
			);
		}

		static void EmitCollectionGuard(
			CodeWriter writer,
			CollectionEventInfo collectionEvent,
			string indent
		)
		{
			writer.WriteLine($"{indent}\t\tif ({collectionEvent.PropertyName} is null)");
			writer.WriteLine($"{indent}\t\t{{");
			writer.WriteLine(
				$"{indent}\t\t\tthrow new global::System.InvalidOperationException(\"Collection property '{collectionEvent.PropertyName}' cannot be null.\");"
			);
			writer.WriteLine($"{indent}\t\t}}");
			writer.WriteLine();
		}

		static void EmitSingleItemBody(
			CodeWriter writer,
			AggregateEventMethodInfo method,
			CollectionEventInfo collectionEvent,
			EventPropertyInfo parameter,
			string hookSuffix,
			string normalizeValidateSuffix,
			string indent
		)
		{
			writer.WriteLine($"{indent}\t\tvar __itemValue = {parameter.ParameterName};");
			writer.WriteLine(
				$"{indent}\t\tOnNormalizing{normalizeValidateSuffix}(ref __itemValue);"
			);
			writer.WriteLine($"{indent}\t\tOnValidating{normalizeValidateSuffix}(__itemValue);");

			var isAddOperation = collectionEvent.Operation == CollectionMutationOperation.Add;
			if (isAddOperation && collectionEvent.IsSet)
			{
				writer.WriteLine();
				writer.WriteLine(
					$"{indent}\t\tif ({collectionEvent.PropertyName}.Contains(__itemValue))"
				);
				writer.WriteLine($"{indent}\t\t{{");
				EmitNoChangeReturn(writer, method.ReturnKind, indent, 3);
				writer.WriteLine($"{indent}\t\t}}");
			}
			else if (!isAddOperation)
			{
				writer.WriteLine();
				writer.WriteLine(
					$"{indent}\t\tif (!{collectionEvent.PropertyName}.Contains(__itemValue))"
				);
				writer.WriteLine($"{indent}\t\t{{");
				EmitNoChangeReturn(writer, method.ReturnKind, indent, 3);
				writer.WriteLine($"{indent}\t\t}}");
			}

			writer.WriteLine();
			writer.WriteLine(
				$"{indent}\t\tvar @event = new global::{method.EventNamespace}.{method.EventName}"
			);
			writer.WriteLine($"{indent}\t\t{{");
			writer.WriteLine($"{indent}\t\t\t{parameter.PropertyName} = __itemValue,");
			writer.WriteLine($"{indent}\t\t}};");
			writer.WriteLine($"{indent}\t\tif (!ShouldApply{hookSuffix}(@event))");
			writer.WriteLine($"{indent}\t\t{{");
			EmitNoChangeReturn(writer, method.ReturnKind, indent, 3);
			writer.WriteLine($"{indent}\t\t}}");
			writer.WriteLine();
			writer.WriteLine($"{indent}\t\tOnRaising{hookSuffix}(ref __itemValue);");
		}

		static void EmitEnumerableBody(
			CodeWriter writer,
			AggregateEventMethodInfo method,
			CollectionEventInfo collectionEvent,
			EventPropertyInfo parameter,
			string hookSuffix,
			string normalizeValidateSuffix,
			string indent
		)
		{
			writer.WriteLine(
				$"{indent}\t\tglobal::System.Collections.Generic.IEnumerable<{collectionEvent.ElementTypeName}> __itemsValue = {parameter.ParameterName};"
			);
			writer.WriteLine(
				$"{indent}\t\tOnNormalizing{normalizeValidateSuffix}(ref __itemsValue);"
			);
			writer.WriteLine($"{indent}\t\tOnValidating{normalizeValidateSuffix}(__itemsValue);");
			writer.WriteLine(
				$"{indent}\t\tvar __eventItems = __itemsValue as {collectionEvent.ElementTypeName}[] ?? [.. __itemsValue];"
			);
			writer.WriteLine($"{indent}\t\tif (__eventItems.Length == 0)");
			writer.WriteLine($"{indent}\t\t{{");
			EmitNoChangeReturn(writer, method.ReturnKind, indent, 3);
			writer.WriteLine($"{indent}\t\t}}");

			var isAddOperation = collectionEvent.Operation == CollectionMutationOperation.Add;
			if (isAddOperation && collectionEvent.IsSet)
			{
				writer.WriteLine();
				writer.WriteLine($"{indent}\t\tvar __hasNewValues = false;");
				writer.WriteLine($"{indent}\t\tforeach (var __item in __eventItems)");
				writer.WriteLine($"{indent}\t\t{{");
				writer.WriteLine(
					$"{indent}\t\t\tif (!{collectionEvent.PropertyName}.Contains(__item))"
				);
				writer.WriteLine($"{indent}\t\t\t{{");
				writer.WriteLine($"{indent}\t\t\t\t__hasNewValues = true;");
				writer.WriteLine($"{indent}\t\t\t\tbreak;");
				writer.WriteLine($"{indent}\t\t\t}}");
				writer.WriteLine($"{indent}\t\t}}");
				writer.WriteLine($"{indent}\t\tif (!__hasNewValues)");
				writer.WriteLine($"{indent}\t\t{{");
				EmitNoChangeReturn(writer, method.ReturnKind, indent, 3);
				writer.WriteLine($"{indent}\t\t}}");
			}
			else if (!isAddOperation)
			{
				writer.WriteLine();
				writer.WriteLine($"{indent}\t\tvar __hasExistingValues = false;");
				writer.WriteLine($"{indent}\t\tforeach (var __item in __eventItems)");
				writer.WriteLine($"{indent}\t\t{{");
				writer.WriteLine(
					$"{indent}\t\t\tif ({collectionEvent.PropertyName}.Contains(__item))"
				);
				writer.WriteLine($"{indent}\t\t\t{{");
				writer.WriteLine($"{indent}\t\t\t\t__hasExistingValues = true;");
				writer.WriteLine($"{indent}\t\t\t\tbreak;");
				writer.WriteLine($"{indent}\t\t\t}}");
				writer.WriteLine($"{indent}\t\t}}");
				writer.WriteLine($"{indent}\t\tif (!__hasExistingValues)");
				writer.WriteLine($"{indent}\t\t{{");
				EmitNoChangeReturn(writer, method.ReturnKind, indent, 3);
				writer.WriteLine($"{indent}\t\t}}");
			}

			writer.WriteLine();
			writer.WriteLine(
				$"{indent}\t\tvar @event = new global::{method.EventNamespace}.{method.EventName}"
			);
			writer.WriteLine($"{indent}\t\t{{");
			writer.WriteLine($"{indent}\t\t\t{parameter.PropertyName} = __eventItems,");
			writer.WriteLine($"{indent}\t\t}};");
			writer.WriteLine($"{indent}\t\tif (!ShouldApply{hookSuffix}(@event))");
			writer.WriteLine($"{indent}\t\t{{");
			EmitNoChangeReturn(writer, method.ReturnKind, indent, 3);
			writer.WriteLine($"{indent}\t\t}}");
			writer.WriteLine();
			writer.WriteLine($"{indent}\t\tOnRaising{hookSuffix}(ref __itemsValue);");
		}

		static void EmitCollectionFinalization(
			CodeWriter writer,
			AggregateEventMethodInfo method,
			string hookSuffix,
			string indent
		)
		{
			writer.WriteLine();
			writer.WriteLine($"{indent}\t\tOnRaised{hookSuffix}(@event);");
			writer.WriteLine($"{indent}\t\tRecordAndApply(@event);");
			writer.WriteLine();
			EmitSuccessReturn(writer, method.ReturnKind, indent, 2);
		}

		static void EmitCollectionTrailingHookDeclarations(
			CodeWriter writer,
			AggregateEventMethodInfo method,
			CollectionEventInfo collectionEvent,
			EventPropertyInfo parameter,
			string hookSuffix,
			string indent
		)
		{
			EmitCa1822Suppression(writer, indent);
			if (collectionEvent.ParameterShape == CollectionParameterShape.Single)
				writer.WriteLine(
					$"{indent}\tpartial void OnRaising{hookSuffix}(ref {collectionEvent.ElementTypeName} {parameter.ParameterName});"
				);
			else
				writer.WriteLine(
					$"{indent}\tpartial void OnRaising{hookSuffix}(ref global::System.Collections.Generic.IEnumerable<{collectionEvent.ElementTypeName}> {parameter.ParameterName});"
				);

			EmitCa1822Suppression(writer, indent);
			writer.WriteLine(
				$"{indent}\tbool ShouldApply{hookSuffix}(global::{method.EventNamespace}.{method.EventName} @event)"
			);
			writer.WriteLine($"{indent}\t{{");
			writer.WriteLine($"{indent}\t\tvar shouldApply = true;");
			writer.WriteLine($"{indent}\t\tOnShouldApply{hookSuffix}(@event, ref shouldApply);");
			writer.WriteLine($"{indent}\t\treturn shouldApply;");
			writer.WriteLine($"{indent}\t}}");
			EmitCa1822Suppression(writer, indent);
			writer.WriteLine(
				$"{indent}\tpartial void OnShouldApply{hookSuffix}(global::{method.EventNamespace}.{method.EventName} @event, ref bool shouldApply);"
			);
			EmitCa1822Suppression(writer, indent);
			writer.WriteLine(
				$"{indent}\tpartial void OnRaised{hookSuffix}(global::{method.EventNamespace}.{method.EventName} @event);"
			);
			EmitCa1822Suppression(writer, indent);
			writer.WriteLine(
				$"{indent}\tpartial void OnApplied{hookSuffix}(global::{method.EventNamespace}.{method.EventName} @event);"
			);
			writer.WriteLine();
		}
	}

	static void GenerateEventClass(
		CodeWriter writer,
		AggregateEventMethodInfo method,
		GenerationLogger? logger
	)
	{
		var storedParameters = method
			.Parameters.Where(static parameter => parameter.IncludeInEvent)
			.ToList();

		logger?.Debug(
			$"Generating event class '{method.EventName}' for method '{method.MethodName}' with {storedParameters.Count} stored parameters and version {method.Version}."
		);

		var hashParameterName = storedParameters.Count == 0 ? "_" : "hash";

		writer.WriteLine(
			$"\tpublic sealed class {method.EventName} : global::Purview.EventSourcing.Aggregates.Events.EventBase"
		);
		writer.WriteLine("\t{");

		foreach (var prop in storedParameters)
		{
			writer.WriteLine(
				$"\t\tpublic {prop.EventPropertyTypeName} {prop.PropertyName} {{ get; set; }} = default!;"
			);
		}

		writer.WriteLine();

		// Emit SchemaVersion override only when it differs from the default (1),
		// but always emit it so consumers can rely on it being present.
		writer.WriteLine($"\t\tpublic override int SchemaVersion => {method.Version};");
		writer.WriteLine();

		writer.WriteLine(
			$"\t\tprotected override void BuildEventHash(ref global::System.HashCode {hashParameterName})"
		);
		writer.WriteLine("\t\t{");

		foreach (var prop in storedParameters)
		{
			writer.WriteLine($"\t\t\t{hashParameterName}.Add({prop.PropertyName});");
		}

		writer.WriteLine("\t\t}");
		writer.WriteLine("\t}");
		writer.WriteLine();
	}

	static void GenerateRegisterEvents(CodeWriter writer, AggregateInfo info, string indent)
	{
		writer.WriteLine($"{indent}\tprotected override void RegisterEvents()");
		writer.WriteLine($"{indent}\t{{");

		foreach (var method in info.Methods)
		{
			writer.WriteLine(
				$"{indent}\t\tRegister<global::{method.EventNamespace}.{method.EventName}>(Apply);"
			);
		}

		writer.WriteLine($"{indent}\t}}");
		writer.WriteLine();
	}

	static void GenerateJsonSerializationSupport(
		CodeWriter writer,
		AggregateInfo info,
		string indent
	)
	{
		writer.WriteLine(
			$"{indent}\tinternal static {info.AggregateClass.TypeName} CreateFromJsonModel({info.AggregateClass.TypeName}JsonModel jsonModel) => new()"
		);
		writer.WriteLine($"{indent}\t\t{{");
		writer.WriteLine(
			$"{indent}\t\t\tDetails = jsonModel.Details ?? new global::Purview.EventSourcing.Aggregates.AggregateDetails(),"
		);

		foreach (var property in info.Properties)
		{
			writer.WriteLine(
				$"{indent}\t\t\t{property.PropertyName} = jsonModel.{property.PropertyName},"
			);
		}

		writer.WriteLine($"{indent}\t\t}};");
		writer.WriteLine();

		writer.WriteLine(
			$"{indent}\tinternal {info.AggregateClass.TypeName}JsonModel ToJsonModel() => new()"
		);
		writer.WriteLine($"{indent}\t\t{{");
		writer.WriteLine($"{indent}\t\t\tDetails = Details,");

		foreach (var property in info.Properties)
		{
			writer.WriteLine($"{indent}\t\t\t{property.PropertyName} = {property.PropertyName},");
		}

		writer.WriteLine($"{indent}\t\t}};");
		writer.WriteLine();
	}

	static void GenerateApplyMethod(
		CodeWriter writer,
		AggregateInfo _,
		AggregateEventMethodInfo method,
		string indent
	)
	{
		if (method.ManualApply)
		{
			writer.WriteLine(
				$"{indent}\tprivate partial void Apply(global::{method.EventNamespace}.{method.EventName} @event);"
			);
			writer.WriteLine();
			return;
		}

		if (method.IsCollectionEvent)
		{
			GenerateCollectionApplyMethod(writer, method, indent);
			return;
		}

		if (method.Parameters.Count == 0)
		{
			writer.WriteLine(
				$"{indent}\tprivate partial void Apply(global::{method.EventNamespace}.{method.EventName} @event);"
			);
			writer.WriteLine();
			return;
		}

		const string eventParameterName = "@event";
		var mappedParameters = method
			.Parameters.Where(static parameter => parameter.HasAggregateProperty)
			.ToList();

		writer.WriteLine(
			$"{indent}\tvoid Apply(global::{method.EventNamespace}.{method.EventName} {eventParameterName})"
		);
		writer.WriteLine($"{indent}\t{{");

		foreach (var prop in mappedParameters)
		{
			writer.WriteLine(
				$"{indent}\t\tvar __previous{prop.AggregatePropertyName} = {prop.AggregatePropertyName};"
			);
		}

		if (mappedParameters.Count > 0)
			writer.WriteLine();

		foreach (var prop in mappedParameters)
		{
			writer.WriteLine(
				$"{indent}\t\t{prop.AggregatePropertyName} = {eventParameterName}.{prop.PropertyName};"
			);
		}

		if (mappedParameters.Count > 0)
			writer.WriteLine();

		foreach (var prop in mappedParameters)
		{
			writer.WriteLine(
				$"{indent}\t\tOn{prop.AggregatePropertyName}Changed(__previous{prop.AggregatePropertyName}, {prop.AggregatePropertyName});"
			);
		}

		var hookSuffix = GetHookName(method.EventName);
		writer.WriteLine($"{indent}\t\tOnApplied{hookSuffix}({eventParameterName});");
		writer.WriteLine($"{indent}\t}}");
		writer.WriteLine();
	}

	static string GetHookName(string eventName)
	{
		if (!eventName.EndsWith("Event", StringComparison.Ordinal))
			eventName += "Event";

		return eventName;
	}

	static void GenerateCollectionApplyMethod(
		CodeWriter writer,
		AggregateEventMethodInfo method,
		string indent
	)
	{
		var collectionEvent = method.CollectionEvent!;
		var parameter = method.Parameters[0];
		const string eventParameterName = "@event";
		var hookSuffix = GetHookName(method.EventName);
		var operationMethod =
			collectionEvent.Operation == CollectionMutationOperation.Add ? "Add" : "Remove";

		writer.WriteLine(
			$"{indent}\tvoid Apply(global::{method.EventNamespace}.{method.EventName} {eventParameterName})"
		);
		writer.WriteLine($"{indent}\t{{");
		writer.WriteLine($"{indent}\t\tif ({collectionEvent.PropertyName} is null)");
		writer.WriteLine($"{indent}\t\t{{");
		writer.WriteLine(
			$"{indent}\t\t\tthrow new global::System.InvalidOperationException(\"Collection property '{collectionEvent.PropertyName}' cannot be null when applying {method.EventName}.\");"
		);
		writer.WriteLine($"{indent}\t\t}}");
		writer.WriteLine();

		if (collectionEvent.ParameterShape == CollectionParameterShape.Single)
		{
			writer.WriteLine(
				$"{indent}\t\t((global::System.Collections.Generic.ICollection<{collectionEvent.ElementTypeName}>)"
					+ $"{collectionEvent.PropertyName}).{operationMethod}({eventParameterName}.{parameter.PropertyName});"
			);
		}
		else
		{
			writer.WriteLine(
				$"{indent}\t\tforeach (var __item in {eventParameterName}.{parameter.PropertyName})"
			);
			writer.WriteLine($"{indent}\t\t{{");
			writer.WriteLine(
				$"{indent}\t\t\t((global::System.Collections.Generic.ICollection<{collectionEvent.ElementTypeName}>)"
					+ $"{collectionEvent.PropertyName}).{operationMethod}(__item);"
			);
			writer.WriteLine($"{indent}\t\t}}");
		}

		writer.WriteLine();
		writer.WriteLine($"{indent}\t\tOnApplied{hookSuffix}({eventParameterName});");
		writer.WriteLine($"{indent}\t}}");
		writer.WriteLine();
	}

	static void GeneratePropertyHookDeclarations(
		CodeWriter writer,
		AggregateInfo info,
		string indent
	)
	{
		var aggregateProperties = info
			.Methods.SelectMany(static method => method.Parameters)
			.Where(static parameter => parameter.HasAggregateProperty)
			.GroupBy(static parameter => parameter.AggregatePropertyName, StringComparer.Ordinal)
			.Select(static group => group.First())
			.ToList();

		foreach (var prop in aggregateProperties)
		{
			EmitCa1822Suppression(writer, indent);
			writer.WriteLine(
				$"{indent}\tpartial void On{prop.AggregatePropertyName}Changing(ref {prop.PropertyTypeName} {prop.ParameterName});"
			);
			EmitCa1822Suppression(writer, indent);
			writer.WriteLine(
				$"{indent}\tpartial void On{prop.AggregatePropertyName}Changed({prop.PropertyTypeName} previous, {prop.PropertyTypeName} current);"
			);
			writer.WriteLine();
		}
	}

	static void GenerateCollectionNormalizationValidationHookDeclarations(
		CodeWriter writer,
		AggregateInfo info,
		string indent
	)
	{
		var declaredKeys = new HashSet<string>(StringComparer.Ordinal);
		foreach (var method in info.Methods.Where(static method => method.IsCollectionEvent))
		{
			var collectionEvent = method.CollectionEvent!;
			var parameter = method.Parameters[0];
			var declarationType =
				collectionEvent.ParameterShape == CollectionParameterShape.Single
					? collectionEvent.ElementTypeName
					: $"global::System.Collections.Generic.IEnumerable<{collectionEvent.ElementTypeName}>";
			var key = $"{collectionEvent.NormalizeValidateHookSuffix}|{declarationType}";
			if (!declaredKeys.Add(key))
				continue;

			EmitCa1822Suppression(writer, indent);
			writer.WriteLine(
				$"{indent}\tpartial void OnNormalizing{collectionEvent.NormalizeValidateHookSuffix}(ref {declarationType} {parameter.ParameterName});"
			);
			EmitCa1822Suppression(writer, indent);
			writer.WriteLine(
				$"{indent}\tpartial void OnValidating{collectionEvent.NormalizeValidateHookSuffix}({declarationType} {parameter.ParameterName});"
			);
			writer.WriteLine();
		}
	}

	static void EmitCa1822Suppression(CodeWriter writer, string indent) =>
		writer.WriteLine(
			$"{indent}\t[global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Performance\", \"CA1822:Mark members as static\", Justification = \"Generated partial hook declaration must match instance signature and cannot be static.\")]"
		);

	static string GetLocalValueName(EventPropertyInfo parameter) =>
		$"__{parameter.ParameterName}Value";

	static string BuildOnCreatingCallArgumentList(List<EventPropertyInfo> parameters) =>
		string.Join(
			", ",
			parameters.Select(static parameter => $"ref {GetWorkingValueName(parameter)}")
		);

	static string BuildOnCreatingDeclarationParameterList(List<EventPropertyInfo> parameters) =>
		string.Join(
			", ",
			parameters.Select(static parameter =>
				$"ref {parameter.PropertyTypeName} {parameter.ParameterName}"
			)
		);

	static void EmitEventCreation(
		CodeWriter writer,
		AggregateEventMethodInfo method,
		List<EventPropertyInfo> storedParameters,
		string indent,
		bool declareVariable
	)
	{
		var declarationPrefix = declareVariable ? "var " : string.Empty;
		writer.WriteLine(
			$"{indent}\t\t{declarationPrefix}@event = new global::{method.EventNamespace}.{method.EventName}"
		);

		if (storedParameters.Count > 0)
		{
			writer.WriteLine($"{indent}\t\t{{");
			foreach (var prop in storedParameters)
			{
				var valueExpression = GetWorkingValueName(prop);
				if (prop.IsNotNull || prop.IsRequired)
					valueExpression += "!";

				writer.WriteLine($"{indent}\t\t\t{prop.PropertyName} = {valueExpression},");
			}

			writer.WriteLine($"{indent}\t\t}};");
		}
		else
		{
			writer.WriteLine($"{indent}\t\t();");
		}
	}

	static string BuildPropertyValueExpression(
		AggregateInfo info,
		AggregateEventMethodInfo method,
		EventPropertyInfo parameter
	)
	{
		var aggregateTypeName = GetAggregateTypeName(info);

		return parameter.ParameterConversionKind switch
		{
			EventParameterConversionKind.None => parameter.ParameterName,
			EventParameterConversionKind.Implicit =>
				$"({parameter.PropertyTypeName}){parameter.ParameterName}",
			EventParameterConversionKind.Create =>
				$"{parameter.PropertyTypeName}.Create({parameter.ParameterName})",
			EventParameterConversionKind.ContextualCreate =>
				$"{parameter.PropertyTypeName}.Create({parameter.ParameterName}, new global::Purview.EventSourcing.ValueObjects.ValueObjectContext<{aggregateTypeName}>(this, MemberName: nameof({parameter.AggregatePropertyName}), EventName: nameof(global::{method.EventNamespace}.{method.EventName})))",
			_ => parameter.ParameterName,
		};
	}

	static string GetAggregateTypeName(AggregateInfo info) =>
		info.AggregateClass.Namespace is null
			? $"global::{info.AggregateClass.TypeName}"
			: $"global::{info.AggregateClass.Namespace}.{info.AggregateClass.TypeName}";

	static string BuildUnchangedCondition(List<EventPropertyInfo> parameters)
	{
		return string.Join(" && ", parameters.Select(BuildUnchangedComparison));
	}

	static string BuildUnchangedComparison(EventPropertyInfo parameter)
	{
		var comparisonValue = GetWorkingValueName(parameter);

		return parameter.UseStringOrdinalComparison
			? $"global::System.String.Equals({parameter.AggregatePropertyName}, {comparisonValue}, global::System.StringComparison.Ordinal)"
			: $"global::System.Collections.Generic.EqualityComparer<{parameter.EqualityComparerTypeName}>.Default.Equals({parameter.AggregatePropertyName}, {comparisonValue})";
	}

	static string GetWorkingValueName(EventPropertyInfo parameter) =>
		parameter.RequiresLocalCopy ? GetLocalValueName(parameter) : parameter.ParameterName;

	static void EmitNoChangeReturn(
		CodeWriter writer,
		EventMethodReturnKind returnKind,
		string indent,
		int indentDepth
	)
	{
		var methodIndent = indent + new string('\t', indentDepth);
		switch (returnKind)
		{
			case EventMethodReturnKind.Void:
				writer.WriteLine($"{methodIndent}return;");
				break;
			case EventMethodReturnKind.Aggregate:
				writer.WriteLine($"{methodIndent}return this;");
				break;
			case EventMethodReturnKind.Bool:
				writer.WriteLine($"{methodIndent}return false;");
				break;
			default:
				writer.WriteLine($"{methodIndent}return;");
				break;
		}
	}

	static void EmitSuccessReturn(
		CodeWriter writer,
		EventMethodReturnKind returnKind,
		string indent,
		int indentDepth
	)
	{
		var methodIndent = indent + new string('\t', indentDepth);
		switch (returnKind)
		{
			case EventMethodReturnKind.Void:
				writer.WriteLine($"{methodIndent}return;");
				break;
			case EventMethodReturnKind.Aggregate:
				writer.WriteLine($"{methodIndent}return this;");
				break;
			case EventMethodReturnKind.Bool:
				writer.WriteLine($"{methodIndent}return true;");
				break;
			default:
				writer.WriteLine($"{methodIndent}return;");
				break;
		}
	}

	static void GenerateInvalidCommandMethodStub(
		CodeWriter writer,
		InvalidAggregateEventMethodInfo method,
		string indent
	)
	{
		var diagnosticIds =
			method.DiagnosticIds.Length > 0
				? string.Join(", ", method.DiagnosticIds)
				: "unknown diagnostic IDs";
		var message = EscapeStringLiteral(
			$"The generated aggregate event method '{method.Signature}' is unavailable because [Event] validation failed. Review the suppressed generator diagnostics for this method ({diagnosticIds})."
		);

		writer.WriteLine($"{indent}\t{method.Signature}");
		writer.WriteLine($"{indent}\t{{");
		writer.WriteLine(
			$"{indent}\t\tthrow new global::System.InvalidOperationException(\"{message}\");"
		);
		writer.WriteLine($"{indent}\t}}");
		writer.WriteLine();
	}

	static string EscapeStringLiteral(string value) =>
		value
			.Replace("\\", "\\\\")
			.Replace("\"", "\\\"")
			.Replace("\r", "\\r")
			.Replace("\n", "\\n")
			.Replace("\t", "\\t");

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases")]
	static string GetAccessModifier(Accessibility accessibility)
	{
		return accessibility switch
		{
			Accessibility.Public => "public",
			Accessibility.Private => "private",
			Accessibility.Internal => "internal",
			Accessibility.Protected => "protected",
			Accessibility.ProtectedOrInternal => "protected internal",
			Accessibility.ProtectedAndInternal => "private protected",
			_ => "internal",
		};
	}

	static void GenerateJsonConverter(CodeWriter writer, AggregateInfo info, string indent)
	{
		writer.WriteLine();
		writer.WriteLine(
			$"{indent}sealed class {info.AggregateClass.TypeName}JsonConverter : global::System.Text.Json.Serialization.JsonConverter<{info.AggregateClass.TypeName}>"
		);
		writer.WriteLine($"{indent}{{");
		writer.WriteLine(
			$"{indent}\tpublic override {info.AggregateClass.TypeName}? Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)"
		);
		writer.WriteLine($"{indent}\t{{");
		writer.WriteLine(
			$"{indent}\t\tvar jsonModel = global::System.Text.Json.JsonSerializer.Deserialize<{info.AggregateClass.TypeName}JsonModel>(ref reader, options);"
		);
		writer.WriteLine($"{indent}\t\tif (jsonModel is null)");
		writer.WriteLine(
			$"{indent}\t\t\tthrow new global::System.Text.Json.JsonException(\"Unable to deserialize {info.AggregateClass.TypeName}.\");"
		);
		writer.WriteLine();
		writer.WriteLine(
			$"{indent}\t\treturn {info.AggregateClass.TypeName}.CreateFromJsonModel(jsonModel);"
		);
		writer.WriteLine($"{indent}\t}}");
		writer.WriteLine();
		writer.WriteLine(
			$"{indent}\tpublic override void Write(global::System.Text.Json.Utf8JsonWriter writer, {info.AggregateClass.TypeName} value, global::System.Text.Json.JsonSerializerOptions options)"
		);
		writer.WriteLine($"{indent}\t{{");
		writer.WriteLine(
			$"{indent}\t\tglobal::System.Text.Json.JsonSerializer.Serialize(writer, value.ToJsonModel(), options);"
		);
		writer.WriteLine($"{indent}\t}}");
		writer.WriteLine($"{indent}}}");
	}

	static void GenerateJsonModel(CodeWriter writer, AggregateInfo info, string indent)
	{
		writer.WriteLine();
		writer.WriteLine($"{indent}sealed class {info.AggregateClass.TypeName}JsonModel");
		writer.WriteLine($"{indent}{{");
		writer.WriteLine(
			$"{indent}\tpublic global::Purview.EventSourcing.Aggregates.AggregateDetails? Details {{ get; set; }} = new();"
		);

		foreach (var property in info.Properties)
		{
			writer.WriteLine(
				$"{indent}\tpublic {property.TypeName} {property.PropertyName} {{ get; set; }} = default!;"
			);
		}

		writer.WriteLine($"{indent}}}");
	}
}
