using Microsoft.CodeAnalysis;

namespace Purview.EventSourcing.SourceGenerator.Aggregate;

static partial class AggregateSourceEmitter
{
	public static void GenerateAggregateSource(AggregateGenerationOutputContext outputContext)
	{
		outputContext.Debug(
			$"Generating source for aggregate '{outputContext.Aggregate.AggregateClass.TypeName}' with {outputContext.Aggregate.Methods.Count} event methods and {outputContext.Aggregate.InvalidMethods.Count} invalid methods."
		);

		outputContext.Writer.WriteAutoGeneratedHeader();

		// Generate event classes in a nested Events namespace
		if (outputContext.Aggregate.Methods.Count > 0)
		{
			foreach (
				var namespaceMethods in outputContext.Aggregate.Methods.GroupBy(
					static method => method.EventNamespace,
					StringComparer.Ordinal
				)
			)
			{
				outputContext.Writer.WriteLine($"namespace {namespaceMethods.Key}");
				outputContext.Writer.WriteLine("{");

				foreach (var method in namespaceMethods)
				{
					GenerateEventClass(outputContext, method);
				}

				outputContext.Writer.WriteLine("}");
				outputContext.Writer.WriteLine();
			}
		}

		// Generate the partial aggregate class in a block-scoped namespace
		// (required because event classes use a different namespace in the same file)
		var accessModifier = GetAccessModifier(outputContext.Aggregate.Accessibility);

		if (outputContext.Aggregate.AggregateClass.Namespace is not null)
		{
			outputContext.Writer.WriteLine(
				$"namespace {outputContext.Aggregate.AggregateClass.Namespace}"
			);
			outputContext.Writer.WriteLine("{");
		}

		var indent = outputContext.Aggregate.AggregateClass.Namespace is not null ? "\t" : "";

		outputContext.Writer.WriteLine(
			$"{indent}[global::System.Text.Json.Serialization.JsonConverter(typeof({outputContext.Aggregate.AggregateClass.TypeName}JsonConverter))]"
		);
		var aggregateBaseClause = outputContext.Aggregate.ShouldDeclareAggregateBase
			? " : global::Purview.EventSourcing.Aggregates.AggregateBase"
			: string.Empty;
		outputContext.Writer.WriteLine(
			$"{indent}{accessModifier} partial class {outputContext.Aggregate.AggregateClass.TypeName}{aggregateBaseClause}"
		);
		outputContext.Writer.WriteLine($"{indent}{{");

		GenerateJsonSerializationSupport(outputContext, indent);

		// Generate RegisterEvents override
		GenerateRegisterEvents(outputContext, indent);

		// Generate Apply methods
		foreach (var method in outputContext.Aggregate.Methods)
		{
			GenerateApplyMethod(outputContext, method, indent);
		}

		// Generate command method implementations
		foreach (var method in outputContext.Aggregate.Methods)
		{
			if (method.IsCollectionEvent)
				CollectionCommandMethodEmitter.Generate(outputContext, method, indent);
			else
				CommandMethodEmitter.Generate(outputContext, method, indent);
		}

		GenerateCollectionNormalizationValidationHookDeclarations(outputContext, indent);
		GeneratePropertyHookDeclarations(outputContext, indent);

		foreach (var method in outputContext.Aggregate.InvalidMethods)
		{
			GenerateInvalidCommandMethodStub(outputContext, method, indent);
		}

		outputContext.Writer.WriteLine($"{indent}}}");

		GenerateJsonConverter(outputContext, indent);
		GenerateJsonModel(outputContext, indent);

		if (outputContext.Aggregate.AggregateClass.Namespace is not null)
		{
			outputContext.Writer.WriteLine("}");
		}
	}

	static void GenerateEventClass(
		AggregateGenerationOutputContext outputContext,
		AggregateEventMethodInfo method
	)
	{
		var storedParameters = method
			.Parameters.Where(static parameter => parameter.IncludeInEvent)
			.ToList();

		outputContext.Debug(
			$"Generating event class '{method.EventName}' for method '{method.MethodName}' with {storedParameters.Count} stored parameters and version {method.Version}."
		);

		var hashParameterName = storedParameters.Count == 0 ? "_" : "hash";

		outputContext.Writer.WriteLine(
			$"\tpublic sealed class {method.EventName} : global::Purview.EventSourcing.Aggregates.Events.EventBase"
		);
		outputContext.Writer.WriteLine("\t{");

		foreach (var prop in storedParameters)
		{
			outputContext.Writer.WriteLine(
				$"\t\tpublic {prop.EventPropertyTypeName} {prop.PropertyName} {{ get; set; }} = default!;"
			);
		}

		outputContext.Writer.WriteLine();

		// Emit SchemaVersion override only when it differs from the default (1),
		// but always emit it so consumers can rely on it being present.
		outputContext.Writer.WriteLine(
			$"\t\tpublic override int SchemaVersion => {method.Version};"
		);
		outputContext.Writer.WriteLine();

		outputContext.Writer.WriteLine(
			$"\t\tprotected override void BuildEventHash(ref global::System.HashCode {hashParameterName})"
		);
		outputContext.Writer.WriteLine("\t\t{");

		foreach (var prop in storedParameters)
		{
			outputContext.Writer.WriteLine($"\t\t\t{hashParameterName}.Add({prop.PropertyName});");
		}

		outputContext.Writer.WriteLine("\t\t}");
		outputContext.Writer.WriteLine("\t}");
		outputContext.Writer.WriteLine();
	}

	static void GenerateRegisterEvents(
		AggregateGenerationOutputContext outputContext,
		string indent
	)
	{
		outputContext.Writer.WriteLine($"{indent}\tprotected override void RegisterEvents()");
		outputContext.Writer.WriteLine($"{indent}\t{{");

		foreach (var method in outputContext.Aggregate.Methods)
		{
			outputContext.Writer.WriteLine(
				$"{indent}\t\tRegister<global::{method.EventNamespace}.{method.EventName}>(Apply);"
			);
		}

		outputContext.Writer.WriteLine($"{indent}\t}}");
		outputContext.Writer.WriteLine();
	}

	static void GenerateJsonSerializationSupport(
		AggregateGenerationOutputContext outputContext,
		string indent
	)
	{
		outputContext.Writer.WriteLine(
			$"{indent}\tinternal static {outputContext.Aggregate.AggregateClass.TypeName} CreateFromJsonModel({outputContext.Aggregate.AggregateClass.TypeName}JsonModel jsonModel) => new()"
		);
		outputContext.Writer.WriteLine($"{indent}\t\t{{");
		outputContext.Writer.WriteLine(
			$"{indent}\t\t\tDetails = jsonModel.Details ?? new global::Purview.EventSourcing.Aggregates.AggregateDetails(),"
		);

		foreach (var property in outputContext.Aggregate.Properties)
		{
			outputContext.Writer.WriteLine(
				$"{indent}\t\t\t{property.PropertyName} = jsonModel.{property.PropertyName},"
			);
		}

		outputContext.Writer.WriteLine($"{indent}\t\t}};");
		outputContext.Writer.WriteLine();

		outputContext.Writer.WriteLine(
			$"{indent}\tinternal {outputContext.Aggregate.AggregateClass.TypeName}JsonModel ToJsonModel() => new()"
		);
		outputContext.Writer.WriteLine($"{indent}\t\t{{");
		outputContext.Writer.WriteLine($"{indent}\t\t\tDetails = Details,");

		foreach (var property in outputContext.Aggregate.Properties)
		{
			outputContext.Writer.WriteLine(
				$"{indent}\t\t\t{property.PropertyName} = {property.PropertyName},"
			);
		}

		outputContext.Writer.WriteLine($"{indent}\t\t}};");
		outputContext.Writer.WriteLine();
	}

	static void GenerateApplyMethod(
		AggregateGenerationOutputContext outputContext,
		AggregateEventMethodInfo method,
		string indent
	)
	{
		if (method.ManualApply)
		{
			outputContext.Writer.WriteLine(
				$"{indent}\tprivate partial void Apply(global::{method.EventNamespace}.{method.EventName} @event);"
			);
			outputContext.Writer.WriteLine();
			return;
		}

		if (method.IsCollectionEvent)
		{
			GenerateCollectionApplyMethod(outputContext, method, indent);
			return;
		}

		if (method.Parameters.Count == 0)
		{
			outputContext.Writer.WriteLine(
				$"{indent}\tprivate partial void Apply(global::{method.EventNamespace}.{method.EventName} @event);"
			);
			outputContext.Writer.WriteLine();
			return;
		}

		const string eventParameterName = "@event";
		var mappedParameters = method
			.Parameters.Where(static parameter => parameter.HasAggregateProperty)
			.ToList();

		outputContext.Writer.WriteLine(
			$"{indent}\tvoid Apply(global::{method.EventNamespace}.{method.EventName} {eventParameterName})"
		);
		outputContext.Writer.WriteLine($"{indent}\t{{");

		foreach (var prop in mappedParameters)
		{
			outputContext.Writer.WriteLine(
				$"{indent}\t\tvar __previous{prop.AggregatePropertyName} = {prop.AggregatePropertyName};"
			);
		}

		if (mappedParameters.Count > 0)
			outputContext.Writer.WriteLine();

		foreach (var prop in mappedParameters)
		{
			outputContext.Writer.WriteLine(
				$"{indent}\t\t{prop.AggregatePropertyName} = {eventParameterName}.{prop.PropertyName};"
			);
		}

		if (mappedParameters.Count > 0)
			outputContext.Writer.WriteLine();

		foreach (var prop in mappedParameters)
		{
			outputContext.Writer.WriteLine(
				$"{indent}\t\tOn{prop.AggregatePropertyName}Changed(__previous{prop.AggregatePropertyName}, {prop.AggregatePropertyName});"
			);
		}

		var hookSuffix = GetHookName(method.EventName);
		outputContext.Writer.WriteLine($"{indent}\t\tOnApplied{hookSuffix}({eventParameterName});");
		outputContext.Writer.WriteLine($"{indent}\t}}");
		outputContext.Writer.WriteLine();
	}

	internal static string GetHookName(string eventName)
	{
		if (!eventName.EndsWith("Event", StringComparison.Ordinal))
			eventName += "Event";

		return eventName;
	}

	static void GenerateCollectionApplyMethod(
		AggregateGenerationOutputContext outputContext,
		AggregateEventMethodInfo method,
		string indent
	)
	{
		var collectionEvent = method.CollectionEvent!;
		var parameter = method.Parameters[0];
		const string eventParameterName = "@event";
		var hookSuffix = GetHookName(method.EventName);
		var operationMethod =
			collectionEvent.Operation == CollectionMutationOperation.Add ? "Add" : "Remove";

		outputContext.Writer.WriteLine(
			$"{indent}\tvoid Apply(global::{method.EventNamespace}.{method.EventName} {eventParameterName})"
		);
		outputContext.Writer.WriteLine($"{indent}\t{{");
		outputContext.Writer.WriteLine($"{indent}\t\tif ({collectionEvent.PropertyName} is null)");
		outputContext.Writer.WriteLine($"{indent}\t\t{{");
		outputContext.Writer.WriteLine(
			$"{indent}\t\t\tthrow new global::System.InvalidOperationException(\"Collection property '{collectionEvent.PropertyName}' cannot be null when applying {method.EventName}.\");"
		);
		outputContext.Writer.WriteLine($"{indent}\t\t}}");
		outputContext.Writer.WriteLine();

		if (collectionEvent.ParameterShape == CollectionParameterShape.Single)
		{
			outputContext.Writer.WriteLine(
				$"{indent}\t\t((global::System.Collections.Generic.ICollection<{collectionEvent.ElementTypeName}>)"
					+ $"{collectionEvent.PropertyName}).{operationMethod}({eventParameterName}.{parameter.PropertyName});"
			);
		}
		else
		{
			outputContext.Writer.WriteLine(
				$"{indent}\t\tforeach (var __item in {eventParameterName}.{parameter.PropertyName})"
			);
			outputContext.Writer.WriteLine($"{indent}\t\t{{");
			outputContext.Writer.WriteLine(
				$"{indent}\t\t\t((global::System.Collections.Generic.ICollection<{collectionEvent.ElementTypeName}>)"
					+ $"{collectionEvent.PropertyName}).{operationMethod}(__item);"
			);
			outputContext.Writer.WriteLine($"{indent}\t\t}}");
		}

		outputContext.Writer.WriteLine();
		outputContext.Writer.WriteLine($"{indent}\t\tOnApplied{hookSuffix}({eventParameterName});");
		outputContext.Writer.WriteLine($"{indent}\t}}");
		outputContext.Writer.WriteLine();
	}

	static void GeneratePropertyHookDeclarations(
		AggregateGenerationOutputContext outputContext,
		string indent
	)
	{
		var aggregateProperties = outputContext
			.Aggregate.Methods.SelectMany(static method => method.Parameters)
			.Where(static parameter => parameter.HasAggregateProperty)
			.GroupBy(static parameter => parameter.AggregatePropertyName, StringComparer.Ordinal)
			.Select(static group => group.First())
			.ToList();

		foreach (var prop in aggregateProperties)
		{
			EmitCa1822Suppression(outputContext, indent);
			outputContext.Writer.WriteLine(
				$"{indent}\tpartial void On{prop.AggregatePropertyName}Changing(ref {prop.PropertyTypeName} {prop.ParameterName});"
			);
			EmitCa1822Suppression(outputContext, indent);
			outputContext.Writer.WriteLine(
				$"{indent}\tpartial void On{prop.AggregatePropertyName}Changed({prop.PropertyTypeName} previous, {prop.PropertyTypeName} current);"
			);
			outputContext.Writer.WriteLine();
		}
	}

	static void GenerateCollectionNormalizationValidationHookDeclarations(
		AggregateGenerationOutputContext outputContext,
		string indent
	)
	{
		var declaredKeys = new HashSet<string>(StringComparer.Ordinal);
		foreach (
			var method in outputContext.Aggregate.Methods.Where(static method =>
				method.IsCollectionEvent
			)
		)
		{
			var collectionEvent = method.CollectionEvent!;
			var parameter = method.Parameters[0];
			var declarationType =
				collectionEvent.ParameterShape == CollectionParameterShape.Single
					? collectionEvent.ElementTypeName
					: $"global::System.Collections.Generic.IEnumerable<{collectionEvent.ElementTypeName}>";
			var key = $"{collectionEvent.NormalizeValidateHookSuffix}|{declarationType}";
			if (!declaredKeys.Add(key))
				continue;

			EmitCa1822Suppression(outputContext, indent);
			outputContext.Writer.WriteLine(
				$"{indent}\tpartial void OnNormalizing{collectionEvent.NormalizeValidateHookSuffix}(ref {declarationType} {parameter.ParameterName});"
			);
			EmitCa1822Suppression(outputContext, indent);
			outputContext.Writer.WriteLine(
				$"{indent}\tpartial void OnValidating{collectionEvent.NormalizeValidateHookSuffix}({declarationType} {parameter.ParameterName});"
			);
			outputContext.Writer.WriteLine();
		}
	}

	internal static void EmitCa1822Suppression(
		AggregateGenerationOutputContext outputContext,
		string indent
	) =>
		outputContext.Writer.WriteLine(
			$"{indent}\t[global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Performance\", \"CA1822:Mark members as static\", Justification = \"Generated partial hook declaration must match instance signature and cannot be static.\")]"
		);

	internal static string GetLocalValueName(EventPropertyInfo parameter) =>
		$"__{parameter.ParameterName}Value";

	internal static string BuildOnCreatingCallArgumentList(List<EventPropertyInfo> parameters) =>
		string.Join(
			", ",
			parameters.Select(static parameter => $"ref {GetWorkingValueName(parameter)}")
		);

	internal static string BuildOnCreatingDeclarationParameterList(
		List<EventPropertyInfo> parameters
	) =>
		string.Join(
			", ",
			parameters.Select(static parameter =>
				$"ref {parameter.PropertyTypeName} {parameter.ParameterName}"
			)
		);

	internal static void EmitEventCreation(
		AggregateGenerationOutputContext outputContext,
		AggregateEventMethodInfo method,
		List<EventPropertyInfo> storedParameters,
		string indent,
		bool declareVariable
	)
	{
		var declarationPrefix = declareVariable ? "var " : string.Empty;
		outputContext.Writer.WriteLine(
			$"{indent}\t\t{declarationPrefix}@event = new global::{method.EventNamespace}.{method.EventName}"
		);

		if (storedParameters.Count > 0)
		{
			outputContext.Writer.WriteLine($"{indent}\t\t{{");
			foreach (var prop in storedParameters)
			{
				var valueExpression = GetWorkingValueName(prop);
				if (prop.IsNotNull || prop.IsRequired)
					valueExpression += "!";

				outputContext.Writer.WriteLine(
					$"{indent}\t\t\t{prop.PropertyName} = {valueExpression},"
				);
			}

			outputContext.Writer.WriteLine($"{indent}\t\t}};");
		}
		else
		{
			outputContext.Writer.WriteLine($"{indent}\t\t();");
		}
	}

	internal static string BuildPropertyValueExpression(
		AggregateGenerationOutputContext outputContext,
		AggregateEventMethodInfo method,
		EventPropertyInfo parameter
	)
	{
		var aggregateTypeName = GetAggregateTypeName(outputContext.Aggregate);

		return parameter.ParameterConversionKind switch
		{
			EventParameterConversionKind.None => parameter.ParameterName,
			EventParameterConversionKind.Implicit =>
				$"({parameter.PropertyTypeName}){parameter.ParameterName}",
			EventParameterConversionKind.Create =>
				$"{parameter.PropertyTypeName}.Create({parameter.ParameterName})",
			EventParameterConversionKind.ContextualCreate =>
				$"{parameter.PropertyTypeName}.Create({parameter.ParameterName}, new global::Purview.EventSourcing.ValueObjects.ValueObjectContext<{aggregateTypeName}>(this, MemberName: nameof({parameter.AggregatePropertyName}), EventName: nameof(global::{method.EventNamespace}.{method.EventName})))",
			_ => parameter.ParameterName,
		};
	}

	static string GetAggregateTypeName(AggregateInfo info) =>
		info.AggregateClass.Namespace is null
			? $"global::{info.AggregateClass.TypeName}"
			: $"global::{info.AggregateClass.Namespace}.{info.AggregateClass.TypeName}";

	internal static string BuildUnchangedCondition(List<EventPropertyInfo> parameters)
	{
		return string.Join(" && ", parameters.Select(BuildUnchangedComparison));
	}

	static string BuildUnchangedComparison(EventPropertyInfo parameter)
	{
		var comparisonValue = GetWorkingValueName(parameter);

		return parameter.UseStringOrdinalComparison
			? $"global::System.String.Equals({parameter.AggregatePropertyName}, {comparisonValue}, global::System.StringComparison.Ordinal)"
			: $"global::System.Collections.Generic.EqualityComparer<{parameter.EqualityComparerTypeName}>.Default.Equals({parameter.AggregatePropertyName}, {comparisonValue})";
	}

	internal static string GetWorkingValueName(EventPropertyInfo parameter) =>
		parameter.RequiresLocalCopy ? GetLocalValueName(parameter) : parameter.ParameterName;

	internal static void EmitNoChangeReturn(
		AggregateGenerationOutputContext outputContext,
		EventMethodReturnKind returnKind,
		string indent,
		int indentDepth
	)
	{
		var methodIndent = indent + new string('\t', indentDepth);
		switch (returnKind)
		{
			case EventMethodReturnKind.Void:
				outputContext.Writer.WriteLine($"{methodIndent}return;");
				break;
			case EventMethodReturnKind.Aggregate:
				outputContext.Writer.WriteLine($"{methodIndent}return this;");
				break;
			case EventMethodReturnKind.Bool:
				outputContext.Writer.WriteLine($"{methodIndent}return false;");
				break;
			default:
				outputContext.Writer.WriteLine($"{methodIndent}return;");
				break;
		}
	}

	internal static void EmitSuccessReturn(
		AggregateGenerationOutputContext outputContext,
		EventMethodReturnKind returnKind,
		string indent,
		int indentDepth
	)
	{
		var methodIndent = indent + new string('\t', indentDepth);
		switch (returnKind)
		{
			case EventMethodReturnKind.Void:
				outputContext.Writer.WriteLine($"{methodIndent}return;");
				break;
			case EventMethodReturnKind.Aggregate:
				outputContext.Writer.WriteLine($"{methodIndent}return this;");
				break;
			case EventMethodReturnKind.Bool:
				outputContext.Writer.WriteLine($"{methodIndent}return true;");
				break;
			default:
				outputContext.Writer.WriteLine($"{methodIndent}return;");
				break;
		}
	}

	static void GenerateInvalidCommandMethodStub(
		AggregateGenerationOutputContext outputContext,
		InvalidAggregateEventMethodInfo method,
		string indent
	)
	{
		var diagnosticIds =
			method.DiagnosticIds.Length > 0
				? string.Join(", ", method.DiagnosticIds)
				: "unknown diagnostic IDs";
		var message = EscapeStringLiteral(
			$"The generated aggregate event method '{method.Signature}' is unavailable because [Event] validation failed. Review the suppressed generator diagnostics for this method ({diagnosticIds})."
		);

		outputContext.Writer.WriteLine($"{indent}\t{method.Signature}");
		outputContext.Writer.WriteLine($"{indent}\t{{");
		outputContext.Writer.WriteLine(
			$"{indent}\t\tthrow new global::System.InvalidOperationException(\"{message}\");"
		);
		outputContext.Writer.WriteLine($"{indent}\t}}");
		outputContext.Writer.WriteLine();
	}

	static string EscapeStringLiteral(string value) =>
		value
			.Replace("\\", "\\\\")
			.Replace("\"", "\\\"")
			.Replace("\r", "\\r")
			.Replace("\n", "\\n")
			.Replace("\t", "\\t");

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases")]
	internal static string GetAccessModifier(Accessibility accessibility)
	{
		return accessibility switch
		{
			Accessibility.Public => "public",
			Accessibility.Private => "private",
			Accessibility.Internal => "internal",
			Accessibility.Protected => "protected",
			Accessibility.ProtectedOrInternal => "protected internal",
			Accessibility.ProtectedAndInternal => "private protected",
			_ => "internal",
		};
	}

	static void GenerateJsonConverter(AggregateGenerationOutputContext outputContext, string indent)
	{
		outputContext.Writer.WriteLine();
		outputContext.Writer.WriteLine(
			$"{indent}sealed class {outputContext.Aggregate.AggregateClass.TypeName}JsonConverter : global::System.Text.Json.Serialization.JsonConverter<{outputContext.Aggregate.AggregateClass.TypeName}>"
		);
		outputContext.Writer.WriteLine($"{indent}{{");
		outputContext.Writer.WriteLine(
			$"{indent}\tpublic override {outputContext.Aggregate.AggregateClass.TypeName}? Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)"
		);
		outputContext.Writer.WriteLine($"{indent}\t{{");
		outputContext.Writer.WriteLine(
			$"{indent}\t\tvar jsonModel = global::System.Text.Json.JsonSerializer.Deserialize<{outputContext.Aggregate.AggregateClass.TypeName}JsonModel>(ref reader, options);"
		);
		outputContext.Writer.WriteLine($"{indent}\t\tif (jsonModel is null)");
		outputContext.Writer.WriteLine(
			$"{indent}\t\t\tthrow new global::System.Text.Json.JsonException(\"Unable to deserialize {outputContext.Aggregate.AggregateClass.TypeName}.\");"
		);
		outputContext.Writer.WriteLine();
		outputContext.Writer.WriteLine(
			$"{indent}\t\treturn {outputContext.Aggregate.AggregateClass.TypeName}.CreateFromJsonModel(jsonModel);"
		);
		outputContext.Writer.WriteLine($"{indent}\t}}");
		outputContext.Writer.WriteLine();
		outputContext.Writer.WriteLine(
			$"{indent}\tpublic override void Write(global::System.Text.Json.Utf8JsonWriter writer, {outputContext.Aggregate.AggregateClass.TypeName} value, global::System.Text.Json.JsonSerializerOptions options)"
		);
		outputContext.Writer.WriteLine($"{indent}\t{{");
		outputContext.Writer.WriteLine(
			$"{indent}\t\tglobal::System.Text.Json.JsonSerializer.Serialize(writer, value.ToJsonModel(), options);"
		);
		outputContext.Writer.WriteLine($"{indent}\t}}");
		outputContext.Writer.WriteLine($"{indent}}}");
	}

	static void GenerateJsonModel(AggregateGenerationOutputContext outputContext, string indent)
	{
		outputContext.Writer.WriteLine();
		outputContext.Writer.WriteLine(
			$"{indent}sealed class {outputContext.Aggregate.AggregateClass.TypeName}JsonModel"
		);
		outputContext.Writer.WriteLine($"{indent}{{");
		outputContext.Writer.WriteLine(
			$"{indent}\tpublic global::Purview.EventSourcing.Aggregates.AggregateDetails? Details {{ get; set; }} = new();"
		);

		foreach (var property in outputContext.Aggregate.Properties)
		{
			outputContext.Writer.WriteLine(
				$"{indent}\tpublic {property.TypeName} {property.PropertyName} {{ get; set; }} = default!;"
			);
		}

		outputContext.Writer.WriteLine($"{indent}}}");
	}
}
