using Microsoft.Extensions.Logging;
using Purview.Telemetry;

namespace Purview.EventSourcing.AzureStorage;

/// <summary>
/// Telemetry logging contract for the Azure Table and Blob Storage event store.
/// </summary>
/// <remarks>
/// An implementation is generated by the Purview telemetry source generator from the
/// <see cref="LoggerAttribute"/> and <see cref="LogAttribute"/> annotations. Each method describes a single
/// event-store operation or failure for observability and diagnostics.
/// </remarks>
[Logger]
public interface ITableEventStoreTelemetry
{
	/// <summary>
	/// Logs that the aggregate was retrieved from the distributed cache.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	[Log(LogLevel.Debug)]
	void AggregateRetrievedFromCache(string aggregateId, string aggregateTypeFullName);

	/// <summary>
	/// Logs that a get-aggregate operation is starting.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	[Log(LogLevel.Debug)]
	void GetAggregateStart(string aggregateId, string aggregateTypeFullName);

	/// <summary>
	/// Logs that getting the aggregate at a specific version failed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="specificVersion">The requested aggregate version.</param>
	/// <param name="exception">The exception that caused the failure.</param>
	[Log(LogLevel.Error)]
	void GetAggregateAtSpecificVersionFailed(
		string aggregateId,
		string aggregateTypeFullName,
		int specificVersion,
		Exception exception
	);

	/// <summary>
	/// Logs that the aggregate was reconstituted by replaying its events.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="aggregateType">The name of the aggregate type.</param>
	/// <param name="eventCount">The number of events applied.</param>
	/// <param name="versionData">The version data captured after replay.</param>
	[Log(LogLevel.Debug)]
	void ReconstitutedAggregateFromEvents(
		string aggregateId,
		string aggregateTypeFullName,
		string aggregateType,
		int eventCount,
		AggregateVersionData versionData
	);

	/// <summary>
	/// Logs that a get-aggregate-at-version operation is starting.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="specificVersion">The requested aggregate version.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	[Log(LogLevel.Debug)]
	void GetAggregateAtSpecificVersionStart(string aggregateId, int specificVersion, string aggregateTypeFullName);

	/// <summary>
	/// Logs that a save was skipped because the aggregate contained no changes.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="aggregateType">The name of the aggregate type.</param>
	[Log(LogLevel.Debug)]
	void SaveContainedNoChanges(string aggregateId, string aggregateTypeFullName, string aggregateType);

	/// <summary>
	/// Logs that an event with an unknown type was skipped during replay.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="aggregateType">The name of the aggregate type.</param>
	/// <param name="eventType">The name of the skipped event type.</param>
	/// <param name="aggregateVersion">The version the event was attempted at.</param>
	[Log(LogLevel.Warning)]
	void SkippedUnknownEvent(
		string aggregateId,
		string aggregateTypeFullName,
		string aggregateType,
		string eventType,
		int aggregateVersion
	);

	/// <summary>
	/// Logs that an event could not be applied to the aggregate during replay.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="aggregateType">The name of the aggregate type.</param>
	/// <param name="eventType">The name of the event type.</param>
	/// <param name="eventTypeFullName">The full name of the event type.</param>
	/// <param name="aggregateVersion">The version the event was attempted at.</param>
	[Log(LogLevel.Warning)]
	void CannotApplyEvent(
		string aggregateId,
		string aggregateTypeFullName,
		string aggregateType,
		string eventType,
		string eventTypeFullName,
		int aggregateVersion
	);

	/// <summary>
	/// Logs that a get-aggregate operation completed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="elapsedMilliseconds">The elapsed time of the operation.</param>
	[Log(LogLevel.Debug)]
	void GetAggregateComplete(string aggregateId, string aggregateTypeFullName, long elapsedMilliseconds);

	/// <summary>
	/// Logs that deserializing a snapshot failed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="exception">The exception that caused the failure.</param>
	[Log(LogLevel.Error)]
	void SnapshotDeserializationFailed(string aggregateId, string aggregateTypeFullName, Exception exception);

	/// <summary>
	/// Logs that reading the aggregate from the distributed cache failed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="exception">The exception that caused the failure.</param>
	[Log(LogLevel.Warning)]
	void CacheGetFailure(string aggregateId, string aggregateTypeFullName, Exception exception);

	/// <summary>
	/// Logs that updating the distributed cache failed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="exception">The exception that caused the failure.</param>
	[Log(LogLevel.Warning)]
	void CacheUpdateFailure(string aggregateId, string aggregateTypeFullName, Exception exception);

	/// <summary>
	/// Logs that a large event is being written to blob storage.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="blobName">The name of the blob.</param>
	/// <param name="length">The length of the serialized event, in bytes.</param>
	/// <param name="fullName">The full name of the event type.</param>
	[Log(LogLevel.Debug)]
	void WritingLargeEvent(string aggregateId, string blobName, long length, string fullName);

	/// <summary>
	/// Logs that the aggregate was deleted.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="aggregateType">The name of the aggregate type.</param>
	[Log(LogLevel.Debug)]
	void AggregateDeleted(string aggregateId, string aggregateTypeFullName, string aggregateType);

	/// <summary>
	/// Logs that the aggregate was restored.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="aggregateType">The name of the aggregate type.</param>
	[Log(LogLevel.Debug)]
	void AggregateRestored(string aggregateId, string aggregateTypeFullName, string aggregateType);

	/// <summary>
	/// Logs that a save operation has been called.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="aggregateType">The name of the aggregate type.</param>
	[Log(LogLevel.Debug)]
	void SaveCalled(string aggregateId, string aggregateTypeFullName, string aggregateType);

	/// <summary>
	/// Logs that persisting the events to storage failed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="httpStatusCode">The HTTP status code returned by the storage operation.</param>
	/// <param name="exception">The exception that caused the failure.</param>
	[Log(LogLevel.Error)]
	void SaveFailedAtStorage(string aggregateId, string aggregateTypeFullName, int httpStatusCode, Exception exception);

	/// <summary>
	/// Logs that the events for the idempotency id were already applied.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="idempotencyId">The idempotency id that was already applied.</param>
	[Log(LogLevel.Debug)]
	void EventsAlreadyApplied(string aggregateId, string idempotencyId);

	/// <summary>
	/// Logs that the save operation failed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="exception">The exception that caused the failure.</param>
	[Log(LogLevel.Error)]
	void SaveFailed(string aggregateId, string aggregateTypeFullName, Exception exception);

	/// <summary>
	/// Logs that an event type could not be resolved.
	/// </summary>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="eventType">The name of the unresolved event type.</param>
	[Log(LogLevel.Warning)]
	void MissingEventType(string aggregateTypeFullName, string eventType);

	/// <summary>
	/// Logs that a get-aggregate-at-version operation completed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="specificVersion">The requested aggregate version.</param>
	/// <param name="elapsedMilliseconds">The elapsed time of the operation.</param>
	[Log(LogLevel.Debug)]
	void GetAggregateAtSpecificVersionComplete(
		string aggregateId,
		string aggregateTypeFullName,
		int specificVersion,
		long elapsedMilliseconds
	);

	/// <summary>
	/// Logs that an event pointing to a blob was skipped because the blob was missing.
	/// </summary>
	/// <param name="partitionKey">The partition key of the event entity.</param>
	/// <param name="rowKey">The row key of the event entity.</param>
	/// <param name="serializedEventType">The serialized event type stored on the pointer.</param>
	/// <param name="blobName">The name of the missing blob.</param>
	[Log(LogLevel.Warning)]
	void SkippedMissingBlobEvent(string partitionKey, string rowKey, string serializedEventType, string blobName);

	/// <summary>
	/// Logs that an event pointing to a blob was skipped because the blob event type name could not be resolved.
	/// </summary>
	/// <param name="partitionKey">The partition key of the event entity.</param>
	/// <param name="rowKey">The row key of the event entity.</param>
	/// <param name="serializedEventType">The serialized event type stored on the pointer.</param>
	/// <param name="blobName">The name of the blob.</param>
	[Log(LogLevel.Warning)]
	void SkippedMissingBlobEventName(string partitionKey, string rowKey, string serializedEventType, string blobName);

	/// <summary>
	/// Logs that the type of an event stored in a blob could not be resolved.
	/// </summary>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="eventType">The name of the event type.</param>
	/// <param name="serializedEventType">The serialized event type stored on the pointer.</param>
	/// <param name="blobEventTypeName">The resolved blob event type name.</param>
	[Log(LogLevel.Warning)]
	void MissingBlobEventType(
		string aggregateTypeFullName,
		string eventType,
		string serializedEventType,
		string blobEventTypeName
	);

	/// <summary>
	/// Logs that removing the aggregate from the distributed cache failed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="exception">The exception that caused the failure.</param>
	[Log(LogLevel.Warning)]
	void CacheRemovalFailure(string aggregateId, string aggregateTypeFullName, Exception exception);

	/// <summary>
	/// Logs that deserializing a persisted event failed.
	/// </summary>
	/// <param name="partitionKey">The partition key of the event entity.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="exception">The exception that caused the failure.</param>
	[Log(LogLevel.Warning)]
	void EventDeserializationFailed(string partitionKey, string aggregateTypeFullName, Exception exception);

	/// <summary>
	/// Logs that the aggregate was successfully saved.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="eventCount">The number of events persisted.</param>
	/// <param name="aggregateType">The name of the aggregate type.</param>
	[Log(LogLevel.Debug)]
	void SavedAggregate(string aggregateId, string aggregateTypeFullName, int eventCount, string aggregateType);

	/// <summary>
	/// Logs that getting the aggregate failed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	/// <param name="exception">The exception that caused the failure.</param>
	[Log(LogLevel.Error)]
	void GetAggregateFailed(string aggregateId, string aggregateTypeFullName, Exception exception);

	/// <summary>
	/// Logs that a stream version entity expected to exist was not found.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="aggregateTypeName">The name of the aggregate type.</param>
	/// <param name="aggregateTypeFullName">The full name of the aggregate type.</param>
	[Log(LogLevel.Warning)]
	void StreamVersionExpectedToExistButNotFound(
		string aggregateId,
		string aggregateTypeName,
		string aggregateTypeFullName
	);

	/// <summary>
	/// Logs that the stream version entity for the aggregate was not found.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	[Log(LogLevel.Debug)]
	void StreamVersionNotFound(string aggregateId);

	/// <summary>
	/// Logs that the stream version entity for the aggregate was found.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="streamVersion">The current stream version.</param>
	/// <param name="aggregateType">The name of the aggregate type.</param>
	/// <param name="isDeleted">Whether the aggregate is marked as deleted.</param>
	[Log(LogLevel.Debug)]
	void StreamVersionFound(string aggregateId, int streamVersion, string aggregateType, bool isDeleted);

	/// <summary>
	/// Logs that reading the stream version entity failed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="streamVersionKey">The row key of the stream version entity.</param>
	/// <param name="exception">The exception that caused the failure.</param>
	[Log(LogLevel.Error)]
	void GetStreamVersionFailed(string aggregateId, string streamVersionKey, Exception exception);

	/// <summary>
	/// Logs that a read of the stream version entity is starting.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="streamVersionKey">The row key of the stream version entity.</param>
	[Log(LogLevel.Debug)]
	void GetStreamVersionStart(string aggregateId, string streamVersionKey);

	/// <summary>
	/// Logs that a read of the stream version entity completed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="streamVersionKey">The row key of the stream version entity.</param>
	/// <param name="elapsedMilliseconds">The elapsed time of the operation.</param>
	[Log(LogLevel.Debug)]
	void GetStreamVersionComplete(string aggregateId, string streamVersionKey, long elapsedMilliseconds);

	/// <summary>
	/// Logs that a permanent delete of the aggregate has been requested.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	[Log(LogLevel.Debug)]
	void PermanentDeleteRequested(string aggregateId);

	/// <summary>
	/// Logs that a permanent delete of the aggregate failed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="exception">The exception that caused the failure.</param>
	[Log(LogLevel.Critical)]
	void PermanentDeleteFailed(string aggregateId, Exception exception);

	/// <summary>
	/// Logs that a permanent delete of the aggregate completed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	[Log(LogLevel.Debug)]
	void PermanentDeleteComplete(string aggregateId);

	/// <summary>
	/// Logs that reading the idempotency marker entity failed.
	/// </summary>
	/// <param name="aggregateId">The id of the aggregate.</param>
	/// <param name="idempotencyId">The idempotency id being checked.</param>
	/// <param name="exception">The exception that caused the failure.</param>
	[Log(LogLevel.Error)]
	void GetIdempotencyMarkerFailed(string aggregateId, string idempotencyId, Exception exception);
}
