<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Testcontainers.Azurite" />
		<PackageReference Include="Testcontainers.CosmosDb" />
		<PackageReference Include="Testcontainers.MongoDb" />
		<PackageReference Include="Testcontainers.MsSql" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\AzureStorage\AzureStorage.csproj" />
		<ProjectReference Include="..\..\src\CosmosDb\CosmosDb.csproj" />
		<ProjectReference Include="..\..\src\MongoDB\MongoDB.csproj" />
		<ProjectReference Include="..\..\src\SqlServer\SqlServer.csproj" />
	</ItemGroup>
</Project>
