<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Testcontainers.Azurite" />
		<PackageReference Include="Testcontainers.CosmosDb" />
		<PackageReference Include="Testcontainers.MongoDb" />
		<PackageReference Include="Testcontainers.MsSql" />
		<PackageReference Include="Testcontainers.PostgreSql" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\AzureStorage\AzureStorage.csproj" />
		<ProjectReference Include="..\..\src\CosmosDb\CosmosDb.csproj" />
		<ProjectReference Include="..\..\src\ImplementationShared\ImplementationShared.csproj" />
		<ProjectReference Include="..\..\src\MongoDB\MongoDB.csproj" />
		<ProjectReference Include="..\..\src\Postgres\Postgres.csproj" />
		<ProjectReference Include="..\..\src\SqlServer\SqlServer.csproj" />
		<!-- Direct reference required when not used via a NuGet package -->
		<ProjectReference
			Include="..\..\src\SourceGenerator\SourceGenerator.csproj"
			OutputItemType="Analyzer"
			ReferenceOutputAssembly="false"
			PrivateAssets="all"
		/>
	</ItemGroup>
</Project>
