// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Purview.EventSourcing.SqlServer.Events.EntityFramework;

#nullable disable

namespace Purview.EventSourcing.SqlServer.Events.EntityFramework.Migrations
{
    [DbContext(typeof(EventStoreDbContext))]
    [Migration("20260412000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Purview.EventSourcing.SqlServer.EntityFramework.EventStoreEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdempotencyId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Payload")
                        .HasColumnType("json");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("AggregateId", "EntityType")
                        .HasDatabaseName("IX_EventStore_AggregateId_EntityType");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AggregateId", "EntityType"), new[] { "Version", "IsDeleted", "AggregateType", "EventType", "IdempotencyId", "Timestamp" });

                    b.HasIndex("AggregateId", "EntityType", "Version")
                        .HasDatabaseName("IX_EventStore_EventRange")
                        .HasFilter("[EntityType] = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AggregateId", "EntityType", "Version"), new[] { "Payload", "EventType", "IdempotencyId", "IsDeleted", "AggregateType", "Timestamp" });

                    b.HasIndex("AggregateType", "EntityType", "IsDeleted")
                        .HasDatabaseName("IX_EventStore_AggregateType_EntityType");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AggregateType", "EntityType", "IsDeleted"), new[] { "AggregateId" });

                    b.ToTable("EventStore", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
