using System.Collections.Frozen;

namespace Purview.EventSourcing.SourceGenerator.Common;

partial class EventVerbMap
{
	static readonly FrozenDictionary<string, string> PastTenseByVerb = new Dictionary<
		string,
		string
	>
	{
		// ── Original entries (Cancel now US-spelled) ──
		{ "Reactivate", "Reactivated" },
		{ "Unpublish", "Unpublished" },
		{ "Reschedule", "Rescheduled" },
		{ "Deactivate", "Deactivated" },
		{ "Unassign", "Unassigned" },
		{ "Unsuspend", "Unsuspended" },
		{ "Unverify", "Unverified" },
		{ "Publish", "Published" },
		{ "Complete", "Completed" },
		{ "Withdraw", "Withdrawn" },
		{ "Restore", "Restored" },
		{ "Archive", "Archived" },
		{ "Approve", "Approved" },
		{ "Decline", "Declined" },
		{ "Schedule", "Scheduled" },
		{ "Suspend", "Suspended" },
		{ "Confirm", "Confirmed" },
		{ "Disable", "Disabled" },
		{ "Enable", "Enabled" },
		{ "Replace", "Replaced" },
		{ "Register", "Registered" },
		{ "Reject", "Rejected" },
		{ "Attach", "Attached" },
		{ "Unlink", "Unlinked" },
		{ "Clear", "Cleared" },
		{ "Cancel", "Canceled" }, // US (UK: Cancelled)
		{ "Create", "Created" },
		{ "Change", "Changed" },
		{ "Update", "Updated" },
		{ "Remove", "Removed" },
		{ "Delete", "Deleted" },
		{ "Set", "Set" },
		{ "Close", "Closed" },
		{ "Start", "Started" },
		{ "Record", "Recorded" },
		{ "Assign", "Assigned" },
		{ "Link", "Linked" },
		{ "Detach", "Detached" },
		{ "Add", "Added" },
		{ "Import", "Imported" },
		{ "Export", "Exported" },
		{ "Mark", "Marked" },
		{ "Verify", "Verified" },
		{ "Increment", "Incremented" },
		{ "Decrement", "Decremented" },
		{ "Submit", "Submitted" },
		{ "Split", "Split" },
		{ "Move", "Moved" },
		{ "Rename", "Renamed" },
		{ "Open", "Opened" },
		{ "Reset", "Reset" },
		// ── CRUD / lifecycle ──
		{ "Edit", "Edited" },
		{ "Modify", "Modified" },
		{ "Save", "Saved" },
		{ "Load", "Loaded" },
		{ "Insert", "Inserted" },
		{ "Append", "Appended" },
		{ "Merge", "Merged" },
		{ "Duplicate", "Duplicated" },
		{ "Clone", "Cloned" },
		{ "Copy", "Copied" },
		{ "Apply", "Applied" },
		{ "Revert", "Reverted" },
		{ "Rollback", "RolledBack" },
		{ "Commit", "Committed" },
		{ "Finish", "Finished" },
		{ "Finalize", "Finalized" }, // US (UK: Finalise)
		{ "Begin", "Begun" },
		{ "End", "Ended" },
		{ "Pause", "Paused" },
		{ "Resume", "Resumed" },
		{ "Stop", "Stopped" },
		{ "Halt", "Halted" },
		{ "Terminate", "Terminated" },
		{ "Abort", "Aborted" },
		{ "Retry", "Retried" },
		{ "Resend", "Resent" },
		{ "Refresh", "Refreshed" },
		{ "Renew", "Renewed" },
		{ "Expire", "Expired" },
		// ── Approval / review / state transitions ──
		{ "Accept", "Accepted" },
		{ "Deny", "Denied" },
		{ "Authorize", "Authorized" }, // US (UK: Authorise)
		{ "Validate", "Validated" },
		{ "Invalidate", "Invalidated" },
		{ "Review", "Reviewed" },
		{ "Flag", "Flagged" },
		{ "Unflag", "Unflagged" },
		{ "Block", "Blocked" },
		{ "Unblock", "Unblocked" },
		{ "Ban", "Banned" },
		{ "Unban", "Unbanned" },
		{ "Lock", "Locked" },
		{ "Unlock", "Unlocked" },
		{ "Grant", "Granted" },
		{ "Revoke", "Revoked" },
		{ "Promote", "Promoted" },
		{ "Demote", "Demoted" },
		{ "Escalate", "Escalated" },
		{ "Resolve", "Resolved" },
		{ "Reopen", "Reopened" },
		{ "Dismiss", "Dismissed" },
		{ "Fail", "Failed" },
		// ── Account / auth / identity ──
		{ "Login", "LoggedIn" },
		{ "Logout", "LoggedOut" },
		{ "SignIn", "SignedIn" },
		{ "SignOut", "SignedOut" },
		{ "SignUp", "SignedUp" },
		{ "Authenticate", "Authenticated" },
		{ "Onboard", "Onboarded" },
		{ "Offboard", "Offboarded" },
		{ "Enroll", "Enrolled" }, // US (UK: Enrol)
		{ "Subscribe", "Subscribed" },
		{ "Unsubscribe", "Unsubscribed" },
		{ "Invite", "Invited" },
		{ "Join", "Joined" },
		{ "Leave", "Left" }, // irregular
		{ "Impersonate", "Impersonated" },
		// ── Commerce / payments / Fulfilment ──
		{ "Purchase", "Purchased" },
		{ "Order", "Ordered" },
		{ "Pay", "Paid" }, // irregular
		{ "Charge", "Charged" },
		{ "Refund", "Refunded" },
		{ "Bill", "Billed" },
		{ "Invoice", "Invoiced" },
		{ "Credit", "Credited" },
		{ "Debit", "Debited" },
		{ "Settle", "Settled" },
		{ "Reconcile", "Reconciled" },
		{ "Capture", "Captured" },
		{ "Void", "Voided" },
		{ "Dispute", "Disputed" },
		{ "Quote", "Quoted" },
		{ "Discount", "Discounted" },
		{ "Ship", "Shipped" },
		{ "Dispatch", "Dispatched" },
		{ "Deliver", "Delivered" },
		{ "Return", "Returned" },
		{ "Fulfill", "Fulfilled" }, // US (UK: Fulfil)
		{ "Pack", "Packed" },
		{ "Unpack", "Unpacked" },
		{ "Stock", "Stocked" },
		{ "Restock", "Restocked" },
		{ "Reserve", "Reserved" },
		{ "Allocate", "Allocated" },
		{ "Deallocate", "Deallocated" },
		{ "Release", "Released" },
		{ "Redeem", "Redeemed" },
		// ── Communication / notification ──
		{ "Send", "Sent" }, // irregular
		{ "Receive", "Received" },
		{ "Notify", "Notified" },
		{ "Alert", "Alerted" },
		{ "Remind", "Reminded" },
		{ "Email", "Emailed" },
		{ "Message", "Messaged" },
		{ "Post", "Posted" },
		{ "Comment", "Commented" },
		{ "Reply", "Replied" },
		{ "Forward", "Forwarded" },
		{ "Broadcast", "Broadcast" }, // also valid: Broadcasted
		{ "View", "Viewed" },
		{ "Acknowledge", "Acknowledged" },
		// ── Data / processing / transform ──
		{ "Process", "Processed" },
		{ "Generate", "Generated" },
		{ "Calculate", "Calculated" },
		{ "Compute", "Computed" },
		{ "Aggregate", "Aggregated" },
		{ "Transform", "Transformed" },
		{ "Convert", "Converted" },
		{ "Parse", "Parsed" },
		{ "Serialize", "Serialized" }, // US (UK: Serialise)
		{ "Deserialize", "Deserialized" }, // US (UK: Deserialise)
		{ "Encode", "Encoded" },
		{ "Decode", "Decoded" },
		{ "Encrypt", "Encrypted" },
		{ "Decrypt", "Decrypted" },
		{ "Compress", "Compressed" },
		{ "Decompress", "Decompressed" },
		{ "Index", "Indexed" },
		{ "Sort", "Sorted" },
		{ "Filter", "Filtered" },
		{ "Group", "Grouped" },
		{ "Map", "Mapped" },
		{ "Scan", "Scanned" },
		{ "Analyze", "Analyzed" }, // US (UK: Analyse)
		{ "Sync", "Synced" },
		{ "Synchronize", "Synchronized" }, // US (UK: Synchronise)
		{ "Migrate", "Migrated" },
		{ "Backup", "BackedUp" },
		{ "Snapshot", "Snapshotted" },
		{ "Truncate", "Truncated" },
		{ "Purge", "Purged" },
		// ── Files / documents / media ──
		{ "Upload", "Uploaded" },
		{ "Download", "Downloaded" },
		{ "Print", "Printed" },
		{ "Sign", "Signed" },
		{ "Stamp", "Stamped" },
		{ "Watermark", "Watermarked" },
		{ "Render", "Rendered" },
		{ "Compile", "Compiled" },
		{ "Deploy", "Deployed" },
		{ "Provision", "Provisioned" },
		{ "Configure", "Configured" },
		{ "Initialize", "Initialized" }, // US (UK: Initialise)
		// ── Quantity / state changes ──
		{ "Adjust", "Adjusted" },
		{ "Recalculate", "Recalculated" },
		{ "Rebalance", "Rebalanced" },
		{ "Scale", "Scaled" },
		{ "Resize", "Resized" },
		{ "Extend", "Extended" },
		{ "Shorten", "Shortened" },
		{ "Expand", "Expanded" },
		{ "Collapse", "Collapsed" },
		{ "Toggle", "Toggled" },
		{ "Select", "Selected" },
		{ "Deselect", "Deselected" },
		{ "Pick", "Picked" },
		{ "Tag", "Tagged" },
		{ "Untag", "Untagged" },
		{ "Label", "Labeled" }, // US (UK: Labelled)
		{ "Categorize", "Categorized" }, // US (UK: Categorise)
		{ "Classify", "Classified" },
		{ "Prioritize", "Prioritized" }, // US (UK: Prioritise)
		{ "Rank", "Ranked" },
		{ "Rate", "Rated" },
		{ "Score", "Scored" },
		{ "Vote", "Voted" },
		// ── Irregular verbs (past tense is not -ed) ──
		{ "Make", "Made" },
		{ "Take", "Took" },
		{ "Give", "Given" },
		{ "Get", "Got" },
		{ "Put", "Put" },
		{ "Cut", "Cut" },
		{ "Hold", "Held" },
		{ "Keep", "Kept" },
		{ "Lose", "Lost" },
		{ "Find", "Found" },
		{ "Buy", "Bought" },
		{ "Sell", "Sold" },
		{ "Bring", "Brought" },
		{ "Catch", "Caught" },
		{ "Teach", "Taught" },
		{ "Think", "Thought" },
		{ "Choose", "Chosen" },
		{ "Run", "Ran" },
		{ "Write", "Written" },
		{ "Draw", "Drawn" },
		{ "Throw", "Thrown" },
		{ "Grow", "Grown" },
		{ "Show", "Shown" },
		{ "Hide", "Hidden" },
		{ "Break", "Broken" },
		{ "Freeze", "Frozen" },
		{ "Forget", "Forgotten" },
		{ "Bind", "Bound" },
		{ "Rebind", "Rebound" },
		{ "Spend", "Spent" },
		{ "Build", "Built" },
		{ "Rebuild", "Rebuilt" },
		{ "Feed", "Fed" },
		{ "Read", "Read" },
		{ "Lead", "Led" },
		{ "Lay", "Laid" },
		{ "Say", "Said" },
		{ "Win", "Won" },
		{ "Hit", "Hit" },
		{ "Cost", "Cost" },
		{ "Quit", "Quit" },
		{ "Shut", "Shut" },
		{ "Bid", "Bid" },
		{ "Spread", "Spread" },
		{ "Cast", "Cast" },
		{ "Recast", "Recast" },
	}.ToFrozenDictionary();

	static readonly (string Prefix, string Suffix)[] PropertySpecificPatterns =
	[
		("Change", "Changed"),
		("Update", "Updated"),
		("Set", "Set"),
		("Clear", "Cleared"),
		("Remove", "Removed"),
	];

	// Modifier prefixes that attach to a following verb rather than acting as the verb.
	// "ForceSave" -> Force + Save -> "ForceSaved" (inflect last, keep order).
	// Matched case-insensitively against the FIRST PascalCase segment.
	static readonly HashSet<string> ModifierPrefixes =
	[
		with(StringComparer.OrdinalIgnoreCase),
		"Force",
		"Bulk",
		"Soft",
		"Hard",
		"Auto",
		"Batch",
		"Mass",
		"Quick",
		"Partial",
		"Full",
	];

	static readonly string[] PastTenseSuffixes =
	[
		.. PastTenseByVerb
			.Select(static pair => pair.Value)
			.Distinct(StringComparer.Ordinal)
			.OrderByDescending(static value => value.Length)
			.ThenBy(static value => value, StringComparer.Ordinal),
	];

	static readonly FrozenDictionary<string, string> VerbPairsByPrefixLength = PastTenseByVerb
		.OrderByDescending(static pair => pair.Key.Length)
		.ThenBy(static pair => pair.Key, StringComparer.Ordinal)
		.ToFrozenDictionary();
}
