using Microsoft.CodeAnalysis.CSharp;

namespace Purview.EventSourcing.SourceGenerator.Common;

static class GeneratedCodeHelpers
{
	public static bool IsGenerated(ISymbol symbol) =>
		symbol.DeclaringSyntaxReferences.Any(static reference => IsGeneratedTree(reference.SyntaxTree));

	public static bool IsGeneratedTree(SyntaxTree tree)
	{
		var root = tree.GetRoot();
		return root.GetLeadingTrivia()
			.Any(static trivia =>
				trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)
				&& trivia.ToString().Contains("<auto-generated", StringComparison.Ordinal)
			);
	}
}
