using Microsoft.Extensions.Logging;
using Purview.Telemetry;

namespace Purview.EventSourcing.ChangeFeed;

/// <summary>
/// Telemetry logging contract for aggregate change-feed notifications.
/// </summary>
/// <remarks>
/// An implementation is generated by the Purview telemetry source generator from the
/// <see cref="LoggerAttribute"/> and <see cref="LogAttribute"/> annotations. Each method describes a single
/// change-feed notification event (start, complete, or failure) for observability and diagnostics.
/// </remarks>
[Logger]
public interface IAggregateChangeFeedNotifierTelemetry
{
	/// <summary>
	/// Logs that an after-save notification is starting for the aggregate.
	/// </summary>
	/// <param name="id">The aggregate id.</param>
	/// <param name="aggregateType">The aggregate type name.</param>
	/// <param name="isNewAggregate">Whether the aggregate is new.</param>
	/// <param name="eventCount">The number of events persisted.</param>
	[Log(LogLevel.Information)]
	void AfterSaveNotificationStart(string id, string aggregateType, bool isNewAggregate, int eventCount);

	/// <summary>
	/// Logs that a change-feed processor is being invoked.
	/// </summary>
	/// <param name="id">The aggregate id.</param>
	/// <param name="changeFeedProcessorType">The change-feed processor type name.</param>
	[Log(LogLevel.Information)]
	void ProcessingStart(string id, string changeFeedProcessorType);

	/// <summary>
	/// Logs that a change-feed processor invocation completed.
	/// </summary>
	/// <param name="id">The aggregate id.</param>
	/// <param name="changeFeedProcessorType">The change-feed processor type name.</param>
	/// <param name="elapsedMilliseconds">The elapsed time of the invocation.</param>
	/// <param name="success">Whether the invocation succeeded.</param>
	[Log(LogLevel.Information)]
	void ProcessingComplete(string id, string changeFeedProcessorType, long elapsedMilliseconds, bool success);

	/// <summary>
	/// Logs that a change-feed processor invocation failed.
	/// </summary>
	/// <param name="id">The aggregate id.</param>
	/// <param name="changeFeedProcessorType">The change-feed processor type name.</param>
	/// <param name="exception">The exception that occurred.</param>
	[Log(LogLevel.Error)]
	void ProcessingFailed(string id, string changeFeedProcessorType, Exception exception);

	/// <summary>
	/// Logs that an after-save notification completed for the aggregate.
	/// </summary>
	/// <param name="id">The aggregate id.</param>
	/// <param name="aggregateType">The aggregate type name.</param>
	/// <param name="isNewAggregate">Whether the aggregate is new.</param>
	/// <param name="eventCount">The number of events persisted.</param>
	/// <param name="elapsedMilliseconds">The elapsed time of the notification.</param>
	[Log(LogLevel.Information)]
	void AfterSaveNotificationComplete(
		string id,
		string aggregateType,
		bool isNewAggregate,
		int eventCount,
		long elapsedMilliseconds
	);

	/// <summary>
	/// Logs that a before-save notification completed for the aggregate.
	/// </summary>
	/// <param name="id">The aggregate id.</param>
	/// <param name="aggregateType">The aggregate type name.</param>
	/// <param name="isNewAggregate">Whether the aggregate is new.</param>
	/// <param name="elapsedMilliseconds">The elapsed time of the notification.</param>
	[Log(LogLevel.Information)]
	void BeforeSaveNotificationComplete(string id, string aggregateType, bool isNewAggregate, long elapsedMilliseconds);

	/// <summary>
	/// Logs that a before-save notification is starting for the aggregate.
	/// </summary>
	/// <param name="id">The aggregate id.</param>
	/// <param name="aggregateType">The aggregate type name.</param>
	/// <param name="isNewAggregate">Whether the aggregate is new.</param>
	[Log(LogLevel.Information)]
	void BeforeSaveNotificationStart(string id, string aggregateType, bool isNewAggregate);

	/// <summary>
	/// Logs that a change-feed notification failed.
	/// </summary>
	/// <param name="id">The aggregate id.</param>
	/// <param name="aggregateType">The aggregate type name.</param>
	/// <param name="exception">The exception that occurred.</param>
	[Log(LogLevel.Error)]
	void FailureNotificationStart(string id, string aggregateType, Exception exception);

	/// <summary>
	/// Logs that a failed change-feed notification completed.
	/// </summary>
	/// <param name="id">The aggregate id.</param>
	/// <param name="aggregateType">The aggregate type name.</param>
	/// <param name="elapsedMilliseconds">The elapsed time of the notification.</param>
	[Log(LogLevel.Information)]
	void FailureNotificationComplete(string id, string aggregateType, long elapsedMilliseconds);

	/// <summary>
	/// Logs that an after-delete notification completed for the aggregate.
	/// </summary>
	/// <param name="id">The aggregate id.</param>
	/// <param name="aggregateType">The aggregate type name.</param>
	/// <param name="elapsedMilliseconds">The elapsed time of the notification.</param>
	[Log(LogLevel.Information)]
	void AfterDeleteNotificationComplete(string id, string aggregateType, long elapsedMilliseconds);

	/// <summary>
	/// Logs that an after-delete notification is starting for the aggregate.
	/// </summary>
	/// <param name="id">The aggregate id.</param>
	/// <param name="aggregateType">The aggregate type name.</param>
	[Log(LogLevel.Information)]
	void AfterDeleteNotificationStart(string id, string aggregateType);

	/// <summary>
	/// Logs that a before-delete notification completed for the aggregate.
	/// </summary>
	/// <param name="id">The aggregate id.</param>
	/// <param name="aggregateType">The aggregate type name.</param>
	/// <param name="elapsedMilliseconds">The elapsed time of the notification.</param>
	[Log(LogLevel.Information)]
	void BeforeDeleteNotificationComplete(string id, string aggregateType, long elapsedMilliseconds);

	/// <summary>
	/// Logs that a before-delete notification is starting for the aggregate.
	/// </summary>
	/// <param name="id">The aggregate id.</param>
	/// <param name="aggregateType">The aggregate type name.</param>
	[Log(LogLevel.Information)]
	void BeforeDeleteNotificationStart(string id, string aggregateType);
}
