<Project Sdk="Microsoft.NET.Sdk">
	<!-- Remove auto-added SharedTestingFramework since this project only tests the source generator -->
	<ItemGroup>
		<ProjectReference Remove="../SharedTestingFramework/SharedTestingFramework.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
		<PackageReference Include="Purview.SourceGeneratorFramework.Testing.TUnit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\EventSourcing\EventSourcing.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Purview.EventSourcing.SourceGenerator" />
		<Using Include="Purview.EventSourcing.SourceGenerator.Common" />
		<Using Include="Purview.EventSourcing.SourceGenerator.Aggregate" />
		<Using Include="Purview.EventSourcing.SourceGenerator.Aggregate.Models" />
		<Using Include="Purview.EventSourcing.SourceGenerator.ValueObject" />
		<Using Include="Purview.EventSourcing.SourceGenerator.ValueObject.Models" />
	</ItemGroup>
</Project>
