<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Label="NuGet Package Values">
		<IsPackable>true</IsPackable>
		<Title>Purview Queryable Snapshot Store for Azure Cosmos DB</Title>
		<Description>Azure Cosmos DB queryable snapshot storage provider for Purview EventSourcing.</Description>
		<PackageId>Purview.EventSourcing.CosmosDb</PackageId>
		<PackageTags>$(PackageTags);purview;dotnet;event-sourcing;event-store;queryable-store;snapshot;azure-cosmosdb;cosmosdb;</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\EventSourcing\EventSourcing.csproj" />
		<ProjectReference Include="..\ImplementationShared\ImplementationShared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="LinqKit" />
		<PackageReference Include="Microsoft.Azure.Cosmos" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Options" />
	</ItemGroup>
</Project>
