<Project>
	<PropertyGroup>
		<NamespacePrefix>Purview.EventSourcing</NamespacePrefix>
		<IsPackable>false</IsPackable>
		<UsePackageJsonVersion>Strict</UsePackageJsonVersion>
		<RepositoryUrl>https://github.com/kjldev/purview-eventsourcing</RepositoryUrl>
	</PropertyGroup>

	<Import Sdk="Purview.DotNetProjectSdk" Project="Sdk.props" />

	<PropertyGroup>
		<NoWarn>$(NoWarn);CS0436;</NoWarn>
		<!-- Ignoring XML comments for now -->
		<NoWarn>$(NoWarn);CS1574;CS1591;</NoWarn>
		<AzureCosmosDisableNewtonsoftJsonCheck>true</AzureCosmosDisableNewtonsoftJsonCheck>
	</PropertyGroup>

	<PropertyGroup Condition="$(IsTestProject) OR $(IsSharedTestingProject)">
		<NoWarn>$(NoWarn);CA1031;CA2234</NoWarn>
	</PropertyGroup>

	<PropertyGroup Label="NuGet package metadata">
		<Authors>Kieron Lanning</Authors>
		<Company>KJL Solutions Ltd.</Company>
		<Copyright>Copyright © $(CurrentYear) KJL Solutions</Copyright>
		<PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageIcon>kjldev-logo.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup Label="NuGet package assets" Condition="'$(IsPackable)' == 'true'">
		<None Include="$(MSBuildThisFileDirectory)../README.md" Pack="true" PackagePath="/" />
		<None Include="$(MSBuildThisFileDirectory)../LICENSE.md" Pack="true" PackagePath="/" />
		<None
			Include="$(MSBuildThisFileDirectory)../assets/images/kjldev-logo.png"
			Pack="true"
			PackagePath="/"
		/>
	</ItemGroup>
</Project>
