using Purview.Telemetry;

namespace Purview.EventSourcing.CosmosDb.Snapshots;

/// <summary>
/// Telemetry used to record metrics for the Azure Cosmos DB snapshot event store.
/// </summary>
/// <remarks>
/// Implementations are generated by the Purview telemetry source generator from the
/// <see cref="Meter"/> attribute on this interface.
/// </remarks>
[Meter]
public interface ICosmosDbSnapshotEventStoreTelemetry
{
	/// <summary>
	/// Records that a snapshot was created for the given aggregate type.
	/// </summary>
	/// <param name="aggregateType">The name of the aggregate type the snapshot was created for.</param>
	[Counter(AutoIncrement = true)]
	void SnapshotCreated(string aggregateType);
}
